<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Media1</name>
   <tag></tag>
   <elementGuidId>44606663-4d52-4980-ae58-7e20e7d585ce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='panel-25639']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#panel-25639</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e91628f1-09fa-413b-b53a-ba229054d333</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>panel-success panel-task topic-activity panel-25639</value>
      <webElementGuid>7f0589f6-ec1d-4fa2-9dd5-7291be5c9752</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>panel-25639</value>
      <webElementGuid>e1661626-a148-4f7d-80c3-57ac9b43cee5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Done  ActivityStandard Practice Media - Text WidgetLast Opened on : 13-Oct-2022 04:35:00 PM.</value>
      <webElementGuid>32ee1dc4-6cce-4e50-81b9-c125380c165b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;panel-25639&quot;)</value>
      <webElementGuid>3c32dda5-cabe-48a8-bc13-21b0fbb16015</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>98b8ff4c-92c9-40d4-8026-49382270c3ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>panel-success panel-task topic-activity panel-25639</value>
      <webElementGuid>7559e084-da42-4052-9724-eddea3f16e82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>panel-25639</value>
      <webElementGuid>72faca0b-32ce-4d96-98d7-155e8796ca4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Done  ActivityStandard Practice Media - Text WidgetLast Opened on : 13-Oct-2022 04:35:00 PM.</value>
      <webElementGuid>308db05b-3504-446f-9f42-559b73763f0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;panel-25639&quot;)</value>
      <webElementGuid>e4ab474f-130c-416d-bc1a-c00dfd252d97</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='panel-25639']</value>
      <webElementGuid>0e5ff72b-5497-4c2d-b705-9be859dfb9b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='topic-2697']/div/div/div/div</value>
      <webElementGuid>34fb7c06-fb65-4fb2-93e1-62d00386397c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='In progress'])[1]/following::div[5]</value>
      <webElementGuid>463c7493-9d8d-4296-a1ce-4ae083ede861</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Media - Standard/Wizard'])[1]/following::div[6]</value>
      <webElementGuid>57b0529c-2317-4a91-a37f-473e87a60018</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div[2]/div[2]/div/div/div/div[2]/div/div/div/div</value>
      <webElementGuid>5abb9017-261a-4d07-ac3a-fb4726e47b3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'panel-25639' and (text() = 'Done  ActivityStandard Practice Media - Text WidgetLast Opened on : 13-Oct-2022 04:35:00 PM.' or . = 'Done  ActivityStandard Practice Media - Text WidgetLast Opened on : 13-Oct-2022 04:35:00 PM.')]</value>
      <webElementGuid>8f4c20ab-d5a8-4ec3-b338-c9dc645d26e6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
