<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Media8</name>
   <tag></tag>
   <elementGuidId>09eb7d3b-e0e2-4d78-ad86-f561a95bbb4a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='panel-25646']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#panel-25646</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b7c6aaf9-21b5-4e7e-a059-0dab4b3e5da1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>panel-task topic-activity panel-25646</value>
      <webElementGuid>afbe42cd-412e-440a-9aa4-31e9ecd3c84e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>panel-25646</value>
      <webElementGuid>73df2dc2-da60-4ed6-8e29-0f6476c1600c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Not Done  ActivityStandard Practice Media - Record Playback WidgetTask not completed.</value>
      <webElementGuid>07dad9d9-f2f8-4c85-b351-d80e5b463a0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;panel-25646&quot;)</value>
      <webElementGuid>7956d67a-fb81-4648-af3c-fe69465e3ba4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a84d1394-9bf4-4eae-b76f-0d2219a1cd42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>panel-task topic-activity panel-25646</value>
      <webElementGuid>f8cb3867-f74e-475c-8ee5-5f0646c0f323</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>panel-25646</value>
      <webElementGuid>9dd5716f-6334-4fa0-8bf4-1ece9845b64c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Not Done  ActivityStandard Practice Media - Record Playback WidgetTask not completed.</value>
      <webElementGuid>0afec947-44d5-436d-8ea0-54a2ca0e936a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;panel-25646&quot;)</value>
      <webElementGuid>1335d4ea-6fdb-46d5-adcf-ba9fcba3b340</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='panel-25646']</value>
      <webElementGuid>8988ae42-f4f9-460b-a172-5d2cc3d97bf1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='topic-2697']/div/div[3]/div[2]/div</value>
      <webElementGuid>c8d37602-a283-413b-9a10-33b53f9c1d7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Standard Practice Media - Collapsible Text'])[1]/following::div[3]</value>
      <webElementGuid>d697661f-306b-48fc-89d9-d640520acbfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Activity'])[7]/following::div[4]</value>
      <webElementGuid>888a515a-e1a9-42f8-95c3-b6cfc9445096</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[3]/div[2]/div</value>
      <webElementGuid>f616a4b0-62bd-4798-b875-de84b652566c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'panel-25646' and (text() = 'Not Done  ActivityStandard Practice Media - Record Playback WidgetTask not completed.' or . = 'Not Done  ActivityStandard Practice Media - Record Playback WidgetTask not completed.')]</value>
      <webElementGuid>6a997366-b799-4582-afc3-1f63ddaa1543</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
