<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Media9</name>
   <tag></tag>
   <elementGuidId>e249e989-b92b-4323-990e-ade4d7483e2e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='panel-25647']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#panel-25647</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f71efbe5-b605-497d-bf8e-5f9449791874</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>panel-task topic-activity panel-25647</value>
      <webElementGuid>246aa65c-3825-4f46-95e0-ec3895a4dfa3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>panel-25647</value>
      <webElementGuid>9e4c9af7-32c0-48a3-b191-b9bdf993aa00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Not Done  ActivityStandard Practice Media - Multiple Image WidgetTask not completed.</value>
      <webElementGuid>d28d5901-a5d5-47fd-9365-443b7d49ca82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;panel-25647&quot;)</value>
      <webElementGuid>9bc6475a-bcab-481a-b483-c95c8f84550e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>074afae0-6b3e-436a-a46c-a8d028beb3a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>panel-task topic-activity panel-25647</value>
      <webElementGuid>145d36a2-88a8-465c-9d76-992391db3e2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>panel-25647</value>
      <webElementGuid>3975e367-f0d0-4b69-b3b1-d4975c540a7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Not Done  ActivityStandard Practice Media - Multiple Image WidgetTask not completed.</value>
      <webElementGuid>4eafc221-0fa0-41f0-b38e-f21510164b3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;panel-25647&quot;)</value>
      <webElementGuid>1bd726b6-a655-4952-8ca0-ea82f94649a1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='panel-25647']</value>
      <webElementGuid>644fbf3b-7909-47fa-bee0-9cf09f27fb6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='topic-2697']/div/div[3]/div[3]/div</value>
      <webElementGuid>50a8420d-3ae1-41a2-820f-b273a5f6c75d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Standard Practice Media - Record Playback Widget'])[1]/following::div[3]</value>
      <webElementGuid>2e776714-4a2c-4037-9cab-526c75ef32d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Activity'])[8]/following::div[4]</value>
      <webElementGuid>823f469d-89ed-4d89-961a-899f8d9ac831</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[3]/div[3]/div</value>
      <webElementGuid>fe21aa47-dc7a-47da-883d-d2249780b2a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'panel-25647' and (text() = 'Not Done  ActivityStandard Practice Media - Multiple Image WidgetTask not completed.' or . = 'Not Done  ActivityStandard Practice Media - Multiple Image WidgetTask not completed.')]</value>
      <webElementGuid>b1732017-798c-4145-b6d6-fdc341320f27</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
