<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Media11</name>
   <tag></tag>
   <elementGuidId>bbdc1e1b-6e4c-410b-bac7-1fa29ef4e134</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='panel-25660']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#panel-25660</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>920abfe8-0f92-4455-84d7-86d41002849e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>panel-task topic-activity panel-25660</value>
      <webElementGuid>9f183afe-d412-4c30-9181-b1275fc28cbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>panel-25660</value>
      <webElementGuid>cec80825-5f39-43da-b9e0-d36271453a42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Not Done  ActivityStandard Practice Media - Checklist WidgetTask not completed.</value>
      <webElementGuid>862ecdc9-995d-4633-a783-fc82d5248a72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;panel-25660&quot;)</value>
      <webElementGuid>034c4dd3-14f9-4d86-a376-bc15185148ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>730573b4-0946-4428-bdce-d330d6b980d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>panel-task topic-activity panel-25660</value>
      <webElementGuid>5cbbbda1-340a-4652-a97a-81734668cfc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>panel-25660</value>
      <webElementGuid>83a11d47-4f58-4414-9189-5de7af5d2fe3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Not Done  ActivityStandard Practice Media - Checklist WidgetTask not completed.</value>
      <webElementGuid>05252337-7883-4a9e-954a-5ad6b7709121</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;panel-25660&quot;)</value>
      <webElementGuid>ca9ca2d6-c836-4362-8384-647e0c3811ea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='panel-25660']</value>
      <webElementGuid>aeb286b0-4cdb-460f-bd2e-ee556b1a4968</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='topic-2697']/div/div[4]/div[2]/div</value>
      <webElementGuid>852a02b4-1965-45a8-9d31-d62629330f26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Standard Practice Media - Multiple Screen Widget'])[1]/following::div[3]</value>
      <webElementGuid>4cba7550-d8e3-491e-9e33-2c1832167923</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Activity'])[10]/following::div[4]</value>
      <webElementGuid>1ec491c9-f95f-48b9-8cb5-8c75af499180</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[4]/div[2]/div</value>
      <webElementGuid>82e0e15c-e914-45b0-9728-e7c42cfb155d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'panel-25660' and (text() = 'Not Done  ActivityStandard Practice Media - Checklist WidgetTask not completed.' or . = 'Not Done  ActivityStandard Practice Media - Checklist WidgetTask not completed.')]</value>
      <webElementGuid>2d52616a-ebd5-47a3-a995-e8a59a7c364c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
