<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Media4</name>
   <tag></tag>
   <elementGuidId>1cc14ec8-edd9-4d7e-9c98-bf54000c3c9c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='panel-25642']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#panel-25642</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b9db1c4d-fd9b-4cbc-8a9e-46971eb84229</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>panel-success panel-task topic-activity panel-25642</value>
      <webElementGuid>ee3ccf32-a8cd-446b-9824-28c95a591d9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>panel-25642</value>
      <webElementGuid>82dc1581-66df-4abf-9f85-e56efcdb9b9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Done  ActivityStandard Practice Media - Video WidgetLast Opened on : 13-Oct-2022 04:44:37 PM.</value>
      <webElementGuid>f391e4e2-be0e-427c-9d8f-6d5bc0802230</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;panel-25642&quot;)</value>
      <webElementGuid>14696cb3-0e2b-4d37-89c9-57e682ac1e2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>7605aa56-a831-47cb-95a4-671aca79f06a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>panel-success panel-task topic-activity panel-25642</value>
      <webElementGuid>909fedaa-2e20-47a7-b396-8a9464e4f56e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>panel-25642</value>
      <webElementGuid>8d49eca3-3d1c-4f21-a4c5-642cf8f9a555</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Done  ActivityStandard Practice Media - Video WidgetLast Opened on : 13-Oct-2022 04:44:37 PM.</value>
      <webElementGuid>5562b88a-ff15-409a-9041-96384cb427ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;panel-25642&quot;)</value>
      <webElementGuid>a3bca440-13ad-4bc1-bd18-a956dcfdb800</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='panel-25642']</value>
      <webElementGuid>c9a116e3-e874-4804-a6b7-2874a419300f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='topic-2697']/div/div[2]/div/div</value>
      <webElementGuid>63cca391-fe18-4468-bffc-bc09f3f83691</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Standard Practice Media - Image Widget'])[1]/following::div[4]</value>
      <webElementGuid>2d649024-cfa7-406c-b202-c923f141d4d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Activity'])[3]/following::div[5]</value>
      <webElementGuid>4cfbba50-b056-4afb-8f43-25bdd89b35a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]/div/div[2]/div/div</value>
      <webElementGuid>a3d4d15a-e38d-401d-9943-12e10e4d7b9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'panel-25642' and (text() = 'Done  ActivityStandard Practice Media - Video WidgetLast Opened on : 13-Oct-2022 04:44:37 PM.' or . = 'Done  ActivityStandard Practice Media - Video WidgetLast Opened on : 13-Oct-2022 04:44:37 PM.')]</value>
      <webElementGuid>94398bd2-3c29-4b46-8b83-3c8a345f343e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
