<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Media3</name>
   <tag></tag>
   <elementGuidId>6e97fe86-1978-4c5d-bb2c-8f32e9e93851</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='panel-25641']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#panel-25641</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2c377924-83b6-4b24-b2f7-4063c2179401</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>panel-success panel-task topic-activity panel-25641</value>
      <webElementGuid>36d76e11-6af8-44e5-b276-c641a564aaf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>panel-25641</value>
      <webElementGuid>88867ea9-ba88-41cd-9b47-99ba9394b1f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Done  ActivityStandard Practice Media - Image WidgetLast Opened on : 13-Oct-2022 04:44:19 PM.</value>
      <webElementGuid>28e7c0d5-32ad-4f7b-8809-ed37f78d06cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;panel-25641&quot;)</value>
      <webElementGuid>c651f362-6ecf-4449-8390-dcd26a3dd4fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d89d7948-c93f-4964-bb7b-330c3ef384b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>panel-success panel-task topic-activity panel-25641</value>
      <webElementGuid>29293531-e788-4999-8ab5-006bd7b42cff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>panel-25641</value>
      <webElementGuid>0fda917d-a487-402b-a672-2a6b43f2a52d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Done  ActivityStandard Practice Media - Image WidgetLast Opened on : 13-Oct-2022 04:44:19 PM.</value>
      <webElementGuid>915843cd-f0f3-41cc-aeb6-33ad77d8d5b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;panel-25641&quot;)</value>
      <webElementGuid>c0067984-3428-4337-923b-31938a68a9fc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='panel-25641']</value>
      <webElementGuid>e23cebc5-48f3-44ae-bb98-d81bacee4093</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='topic-2697']/div/div/div[3]/div</value>
      <webElementGuid>c7ab7c53-f1b0-437c-84d0-674920568665</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Standard Practice Media - Boxed Text Widget'])[1]/following::div[3]</value>
      <webElementGuid>f2284005-3b7c-424b-aa45-08e335f23c9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Activity'])[2]/following::div[4]</value>
      <webElementGuid>1a92f9f0-d7f5-4904-b8a2-47fb06c73ba9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[2]/div/div/div[3]/div</value>
      <webElementGuid>48d646ef-cac0-46c7-b6c5-6c0fac3dc679</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'panel-25641' and (text() = 'Done  ActivityStandard Practice Media - Image WidgetLast Opened on : 13-Oct-2022 04:44:19 PM.' or . = 'Done  ActivityStandard Practice Media - Image WidgetLast Opened on : 13-Oct-2022 04:44:19 PM.')]</value>
      <webElementGuid>bbaf5cf2-9dc7-48c7-a8b5-5d942bc91b27</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
