<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Media7</name>
   <tag></tag>
   <elementGuidId>00a28483-a9a7-4bda-9c59-f185d74aee66</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='panel-25645']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#panel-25645</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>534da6bd-1b2a-4340-a6a4-953645ebaef3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>panel-success panel-task topic-activity panel-25645</value>
      <webElementGuid>8877ad8c-4294-492e-b37f-4dc4bf69791f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>panel-25645</value>
      <webElementGuid>c6588e2b-8395-46e8-bf47-32d3ddb96b31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Done  ActivityStandard Practice Media - Collapsible TextLast Opened on : 13-Oct-2022 04:47:11 PM.</value>
      <webElementGuid>a5d643e1-ef34-4d2f-a311-2f9846440dde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;panel-25645&quot;)</value>
      <webElementGuid>fd57291e-9e01-46f3-839f-44a3d3b0b6c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>4afc9947-695a-43dd-9e01-dcddb3e4ad16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>panel-success panel-task topic-activity panel-25645</value>
      <webElementGuid>13f02650-e24e-420c-bd39-e990577806cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>panel-25645</value>
      <webElementGuid>4e49589d-6297-44c7-ae43-fa16cfc402b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Done  ActivityStandard Practice Media - Collapsible TextLast Opened on : 13-Oct-2022 04:47:11 PM.</value>
      <webElementGuid>2a69ef42-4de6-47aa-b764-889333ab972a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;panel-25645&quot;)</value>
      <webElementGuid>39a41fa8-a6f4-4337-927d-2a9a4f5d0d4c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='panel-25645']</value>
      <webElementGuid>f2aaafe3-1598-4591-9e51-aca4928eaab4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='topic-2697']/div/div[3]/div/div</value>
      <webElementGuid>0b37d6d3-200c-4dc3-8d01-60979257a5f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Standard Practice Media - Document Widget'])[1]/following::div[4]</value>
      <webElementGuid>54c46928-b375-476f-9c48-9385c672c12b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Activity'])[6]/following::div[5]</value>
      <webElementGuid>027eb538-4964-4a61-87aa-3b48d98254d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[3]/div/div</value>
      <webElementGuid>771380fc-f533-49a9-a22f-03411bdf94ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'panel-25645' and (text() = 'Done  ActivityStandard Practice Media - Collapsible TextLast Opened on : 13-Oct-2022 04:47:11 PM.' or . = 'Done  ActivityStandard Practice Media - Collapsible TextLast Opened on : 13-Oct-2022 04:47:11 PM.')]</value>
      <webElementGuid>5338375d-5608-4a17-b451-e245a742f788</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
