<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Media10</name>
   <tag></tag>
   <elementGuidId>72b8649b-667d-433a-a113-3e9efe1fe736</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='panel-25659']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#panel-25659</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>80d09e32-0045-447a-8baa-86f726218ba5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>panel-task topic-activity panel-25659</value>
      <webElementGuid>0c12b7be-39f5-496c-80db-abe668b032c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>panel-25659</value>
      <webElementGuid>6c01f8a1-f210-4661-a3d7-28544e935c84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Not Done  ActivityStandard Practice Media - Multiple Screen WidgetTask not completed.</value>
      <webElementGuid>1411defb-2c7c-42f3-8a73-e9ba36a97285</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;panel-25659&quot;)</value>
      <webElementGuid>e67e96e1-7965-4698-8273-9c9ee4a599a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>4f9e5b21-97c6-453f-accf-36d99ae26122</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>panel-task topic-activity panel-25659</value>
      <webElementGuid>17775617-6624-46a0-adbc-9e0ac329bbb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>panel-25659</value>
      <webElementGuid>8a53be72-d029-49ee-aa57-9922a8980e6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Not Done  ActivityStandard Practice Media - Multiple Screen WidgetTask not completed.</value>
      <webElementGuid>be3d9afc-46a9-40d4-8c1a-b991cfa1c042</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;panel-25659&quot;)</value>
      <webElementGuid>8f01354a-6249-49ef-b618-58e7a4947c0e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='panel-25659']</value>
      <webElementGuid>7447c94a-989b-430f-babc-2b01c4977b60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='topic-2697']/div/div[4]/div/div</value>
      <webElementGuid>88966af8-9c6a-4b75-a9ca-7fa718c3c1d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Standard Practice Media - Multiple Image Widget'])[1]/following::div[4]</value>
      <webElementGuid>9613d848-1176-4048-a07d-cae274f61bb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Activity'])[9]/following::div[5]</value>
      <webElementGuid>09f9627a-cb07-42f5-b7ef-a30e15bf3ed4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[4]/div/div</value>
      <webElementGuid>895d6555-b32b-490d-befd-ded45395a4c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'panel-25659' and (text() = 'Not Done  ActivityStandard Practice Media - Multiple Screen WidgetTask not completed.' or . = 'Not Done  ActivityStandard Practice Media - Multiple Screen WidgetTask not completed.')]</value>
      <webElementGuid>b20a25e4-00b4-4be8-bf18-a4b2c1509860</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
