<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Media6</name>
   <tag></tag>
   <elementGuidId>7c59330c-86c7-4eee-9e9c-9284fd19949a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='panel-25644']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#panel-25644</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>512add51-554e-4108-85f2-f3e5e59e26d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>panel-success panel-task topic-activity panel-25644</value>
      <webElementGuid>a95a16e4-32e6-48ba-b130-43f49ce1cc0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>panel-25644</value>
      <webElementGuid>bbbc4c98-16be-47ba-ab71-ad23955d9a75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Done  ActivityStandard Practice Media - Document WidgetLast Opened on : 13-Oct-2022 04:45:36 PM.</value>
      <webElementGuid>62395762-57d0-4033-88c2-3e697ed398bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;panel-25644&quot;)</value>
      <webElementGuid>0dd37ccc-2b87-4e24-b286-fa96325e6752</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8dda0c7a-96f8-4b69-9097-d64d4a8f8182</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>panel-success panel-task topic-activity panel-25644</value>
      <webElementGuid>478f0d21-fe98-411e-8a28-69db9d59ce45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>panel-25644</value>
      <webElementGuid>bfd20d8e-79ef-42fa-a32e-21592e57cfd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Done  ActivityStandard Practice Media - Document WidgetLast Opened on : 13-Oct-2022 04:45:36 PM.</value>
      <webElementGuid>8ef0ef42-9407-49c4-b021-0adfb4ea772a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;panel-25644&quot;)</value>
      <webElementGuid>c0c2c5a9-c76a-4f77-81eb-450bd81414e0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='panel-25644']</value>
      <webElementGuid>f51c0d11-6a10-4821-9ce6-0051876e3237</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='topic-2697']/div/div[2]/div[3]/div</value>
      <webElementGuid>7e622f31-5442-4707-9569-c76041152c7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Standard Practice Media - Audio Widget'])[1]/following::div[3]</value>
      <webElementGuid>8938515f-3b70-40e4-95d5-3d0b96eeea0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Activity'])[5]/following::div[4]</value>
      <webElementGuid>2fc78ceb-508a-4b4b-9fb3-bd080c7edec5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div[3]/div</value>
      <webElementGuid>4d7f9d4f-5d48-42b7-895f-474403fcd88c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'panel-25644' and (text() = 'Done  ActivityStandard Practice Media - Document WidgetLast Opened on : 13-Oct-2022 04:45:36 PM.' or . = 'Done  ActivityStandard Practice Media - Document WidgetLast Opened on : 13-Oct-2022 04:45:36 PM.')]</value>
      <webElementGuid>83d4de3f-874c-4a35-a808-39ed13f33a91</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
