<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Media2</name>
   <tag></tag>
   <elementGuidId>4d103e56-a03f-416c-b97c-288c6167601e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='panel-25640']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#panel-25640</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>cbf5ae18-7b7a-4eaa-a7d2-9503c1990b66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>panel-success panel-task topic-activity panel-25640</value>
      <webElementGuid>156dd88a-8294-409c-a636-fa2cfc74ecb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>panel-25640</value>
      <webElementGuid>f9beba75-f66b-4dae-a47b-4266e71f6a10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Done  ActivityStandard Practice Media - Boxed Text WidgetLast Opened on : 13-Oct-2022 04:44:02 PM.</value>
      <webElementGuid>a264c50e-d06e-4343-b114-e9fbdc270770</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;panel-25640&quot;)</value>
      <webElementGuid>693dd460-4526-48e1-95a7-69c0636e3b7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>6061b9a8-23bf-4643-b388-5e6a21dd926e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>panel-success panel-task topic-activity panel-25640</value>
      <webElementGuid>b6a31dec-eba7-4e18-8d77-115901c7b0ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>panel-25640</value>
      <webElementGuid>eeda8521-4684-4fb5-9477-ac850131dbe2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Done  ActivityStandard Practice Media - Boxed Text WidgetLast Opened on : 13-Oct-2022 04:44:02 PM.</value>
      <webElementGuid>c7c0e56b-ac54-428a-a2c7-a6c2858b5599</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;panel-25640&quot;)</value>
      <webElementGuid>377e84fc-e3ed-4e9f-bfba-9fe544e6d3cc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='panel-25640']</value>
      <webElementGuid>04af11da-9d67-4815-a6cb-012866c1a9e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='topic-2697']/div/div/div[2]/div</value>
      <webElementGuid>3fde1d4b-ed2c-47e7-a5d3-f30ab24363be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Standard Practice Media - Text Widget'])[1]/following::div[3]</value>
      <webElementGuid>6fa001c5-a1c0-4bed-b157-bad74515def3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Activity'])[1]/following::div[4]</value>
      <webElementGuid>8044edab-c614-4b6d-b247-01f6f15cc888</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div[2]/div[2]/div/div/div/div[2]/div/div/div[2]/div</value>
      <webElementGuid>7a00f9f0-6fe5-4ff4-b2ce-af9c37d8fe06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'panel-25640' and (text() = 'Done  ActivityStandard Practice Media - Boxed Text WidgetLast Opened on : 13-Oct-2022 04:44:02 PM.' or . = 'Done  ActivityStandard Practice Media - Boxed Text WidgetLast Opened on : 13-Oct-2022 04:44:02 PM.')]</value>
      <webElementGuid>45c6dc60-acc5-4bdc-acf3-bccf4fdcf555</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
