<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Media5</name>
   <tag></tag>
   <elementGuidId>fc49f2f2-7401-436b-9316-febb5524dfe8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='panel-25643']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#panel-25643</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>17e7d0bb-82b2-4f83-bdd2-14ffb20deb36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>panel-success panel-task topic-activity panel-25643</value>
      <webElementGuid>9067bd4c-035b-49ca-912a-e552f788b1b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>panel-25643</value>
      <webElementGuid>d584a6a9-4002-46eb-94ad-38e40a969fcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Done  ActivityStandard Practice Media - Audio WidgetLast Opened on : 13-Oct-2022 04:45:14 PM.</value>
      <webElementGuid>fbac9dfe-0563-4aef-b93e-ac54c7aa12f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;panel-25643&quot;)</value>
      <webElementGuid>7d423753-5c22-47ce-ae9a-6c1763ce8de6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>11e05f84-5f0a-4672-a9ad-2d6b48abbb40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>panel-success panel-task topic-activity panel-25643</value>
      <webElementGuid>6498c5e7-e01b-4286-a5af-295fbff53056</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>panel-25643</value>
      <webElementGuid>6466d895-1909-4c5b-9ea4-87ea81fa4a5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Done  ActivityStandard Practice Media - Audio WidgetLast Opened on : 13-Oct-2022 04:45:14 PM.</value>
      <webElementGuid>40893db9-a54c-480b-a338-8690b798cd76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;panel-25643&quot;)</value>
      <webElementGuid>dc1c4210-f947-4550-b9d4-d5125f264e43</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='panel-25643']</value>
      <webElementGuid>9aa76a55-23b6-4c3a-99e7-8a8e09557dc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='topic-2697']/div/div[2]/div[2]/div</value>
      <webElementGuid>9dadb831-8394-4f56-a549-58b46c83b6c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Standard Practice Media - Video Widget'])[1]/following::div[3]</value>
      <webElementGuid>645bc285-3bdb-4723-bfae-9fa009cee116</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Activity'])[4]/following::div[4]</value>
      <webElementGuid>8c309e5f-0d67-4514-9270-82b966ddcd95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div[2]/div</value>
      <webElementGuid>2b90b663-407d-4148-83a0-5b9b71839337</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'panel-25643' and (text() = 'Done  ActivityStandard Practice Media - Audio WidgetLast Opened on : 13-Oct-2022 04:45:14 PM.' or . = 'Done  ActivityStandard Practice Media - Audio WidgetLast Opened on : 13-Oct-2022 04:45:14 PM.')]</value>
      <webElementGuid>fdb244cf-a797-4634-921c-c3b02c618f75</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
