<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Save1</name>
   <tag></tag>
   <elementGuidId>f6220444-1098-4376-a67f-549854237782</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@name='checkAnswerButton'][1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button[name=&quot;checkAnswerButton&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e9eb2328-269f-4957-b045-3760ca5386e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary practiceButton</value>
      <webElementGuid>da835a24-5272-44a2-8d5f-843d1f819b52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>checkAnswerButton</value>
      <webElementGuid>6f7779d0-e8fa-44b3-b044-25e7b78942c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Please select an answer!</value>
      <webElementGuid>9c5b68e9-874f-4b8d-a2fd-4fa7b930424f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Save</value>
      <webElementGuid>82f6a9c0-3dc3-4b56-b449-16d9add3e88c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dragAndDropMainPanel&quot;)/div[@class=&quot;grid-stack-item-content le-panel grid-stack-item ui-draggable ui-resizable ui-resizable-autohide ui-draggable-disabled ui-resizable-disabled&quot;]/div[1]/div[@class=&quot;le-widget preview-widget ae-widget&quot;]/div[@class=&quot;ibox float-e-margins&quot;]/div[@class=&quot;ibox-content&quot;]/div[@class=&quot;checklist-control&quot;]/button[@class=&quot;btn btn-primary practiceButton&quot;]</value>
      <webElementGuid>b0c4d18c-a0e9-47b4-ba07-97a29e703385</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@name='checkAnswerButton']</value>
      <webElementGuid>ce09691c-7a19-49d8-b212-ffbfe62de053</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dragAndDropMainPanel']/div/div/div/div/div/div[3]/button</value>
      <webElementGuid>a4b3c007-5474-45b0-8f13-dad1fbbdc153</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Incorrect answer'])[3]/following::button[1]</value>
      <webElementGuid>47910895-c047-480b-b7e6-7cf0d940724c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Correct answer'])[3]/following::button[1]</value>
      <webElementGuid>b8cdb339-8f85-4ad3-adee-d8d638af0a00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Checklist Widget'])[2]/preceding::button[1]</value>
      <webElementGuid>c0906efb-42d3-4164-abd9-4e47b21fa534</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lorem Ipsum'])[2]/preceding::button[1]</value>
      <webElementGuid>ec91fe9c-9b36-4863-bc83-0596d3ed47b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Save']/parent::*</value>
      <webElementGuid>1faccd91-2e1a-4cff-a1ce-cf4af06bfb64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>f933e8f6-4e6f-41c7-bc0b-8aa1fdc0a872</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@name = 'checkAnswerButton' and @title = 'Please select an answer!' and (text() = 'Save' or . = 'Save')]</value>
      <webElementGuid>74c43efa-36a5-4d3b-9a12-acbeb34e3d38</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
