<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Save2</name>
   <tag></tag>
   <elementGuidId>b5c70537-4111-4ac3-a6e0-4faa26dae3bf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;dragAndDropMainPanel&quot;]/div/div[1]/div[2]/div/div/div[3]/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button[name=&quot;checkAnswerButton&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8019dd35-3fd8-4053-91b0-c3ddd1d1cce9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary practiceButton</value>
      <webElementGuid>064b42e9-a9d3-4c10-8d50-616766af0871</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>checkAnswerButton</value>
      <webElementGuid>1155e2ef-2b8e-465e-b279-9d0fac7af88c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Please select an answer!</value>
      <webElementGuid>09f3491f-cc10-445c-a2cd-43c43fe3f4b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Save</value>
      <webElementGuid>d8a21a1f-a09b-469f-bade-0e3cf04bc6e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dragAndDropMainPanel&quot;)/div[@class=&quot;grid-stack-item-content le-panel grid-stack-item ui-draggable ui-resizable ui-resizable-autohide ui-draggable-disabled ui-resizable-disabled&quot;]/div[1]/div[@class=&quot;le-widget preview-widget ae-widget&quot;]/div[@class=&quot;ibox float-e-margins&quot;]/div[@class=&quot;ibox-content&quot;]/div[@class=&quot;checklist-control&quot;]/button[@class=&quot;btn btn-primary practiceButton&quot;]</value>
      <webElementGuid>0cdb81ab-2be6-426f-b009-d10e2e89bea3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@name='checkAnswerButton']</value>
      <webElementGuid>71f6d938-9233-4ce7-af0b-54e1aa40d71c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dragAndDropMainPanel']/div/div/div/div/div/div[3]/button</value>
      <webElementGuid>16679ae8-96c4-4b51-bd4a-9e5e759c7d75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Incorrect answer'])[3]/following::button[1]</value>
      <webElementGuid>26599d1e-1bb3-4de5-995d-57d64a0530ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Correct answer'])[3]/following::button[1]</value>
      <webElementGuid>638f4bf3-6a6f-4803-9849-ccfcfdcf3bce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Checklist Widget'])[2]/preceding::button[1]</value>
      <webElementGuid>6c718013-6416-4b8e-b02a-282b412cf81c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lorem Ipsum'])[2]/preceding::button[1]</value>
      <webElementGuid>5ce35fb2-ac3b-4e89-8530-034bbb4be8ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Save']/parent::*</value>
      <webElementGuid>7150325b-d224-4dfd-af89-3cfba7efb041</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>8cd44b62-a65d-4834-8f3d-2a3b3d4e070b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@name = 'checkAnswerButton' and @title = 'Please select an answer!' and (text() = 'Save' or . = 'Save')]</value>
      <webElementGuid>a95576ab-f782-4a99-a3c3-9753360396aa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
