<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Record2</name>
   <tag></tag>
   <elementGuidId>f29afa54-521d-4d13-be6a-cd9f6122b4be</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@id='btnRecord'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>38efd204-6385-4c20-aafa-d361156fa18e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btn-record</value>
      <webElementGuid>3e6a8c3e-210a-40fd-8d56-d5f0b2559f31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnRecord</value>
      <webElementGuid>5a179410-ca82-4490-af2d-011f08688123</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Record And Playback 2 Record Audio</value>
      <webElementGuid>c4ac67d7-1792-4cb1-9a34-f5d262b7af65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-recording-id</name>
      <type>Main</type>
      <value>K9rs1ANi</value>
      <webElementGuid>a62fcb2d-a2f4-4864-9ffa-e31ed09d38a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-allow-retry</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>0e83e5e3-1b91-4f0b-822b-1746fb50143d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-timer</name>
      <type>Main</type>
      <value>60</value>
      <webElementGuid>6df42192-9e4e-4592-8be1-1d8e8bdedb4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>42eaaba6-6fa3-456c-89e1-700d4fc1f67e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Record Audio</value>
      <webElementGuid>7c3bf67d-d1da-4b00-aa67-c331e145a027</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dragAndDropMainPanel&quot;)/div[@class=&quot;grid-stack-item-content le-panel grid-stack-item ui-draggable ui-resizable ui-resizable-autohide ui-draggable-disabled ui-resizable-disabled&quot;]/div[1]/div[@class=&quot;le-widget ae-widget preview-widget&quot;]/div[@class=&quot;ibox float-e-margins&quot;]/div[@class=&quot;ibox-content&quot;]/div[@class=&quot;recorder-container list-question rclick-copy-area&quot;]/div[@class=&quot;ibox float-e-margins&quot;]/div[@class=&quot;recorder-container list-question ae-widget-wrap ibox question panel-suppressed-off&quot;]/div[@class=&quot;ae-content p-sm ibox-content panel-suppressed-off&quot;]/div[@class=&quot;recorder-main-control p-h-sm m-b&quot;]/span[1]/button[@id=&quot;btnRecord&quot;]</value>
      <webElementGuid>192a843a-634b-43ea-9565-2d9421258ef6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@id='btnRecord'])[2]</value>
      <webElementGuid>284787b5-a52f-4e13-91de-777a50908b4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dragAndDropMainPanel']/div/div/div[2]/div/div/div[2]/div/div/div[2]/div/span/button</value>
      <webElementGuid>38d0831a-815a-479f-8b01-09d9c1ec2533</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Record and Playback'])[2]/following::button[1]</value>
      <webElementGuid>574190d0-cfd5-4d95-a7d7-3c8d9f5fbfe6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submit'])[1]/following::button[1]</value>
      <webElementGuid>060962f7-5292-4b33-9a45-a7359a62b14b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submit'])[2]/preceding::button[1]</value>
      <webElementGuid>a852fdf2-f2bd-4d6f-9eb7-dc48c3f0102e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Next'])[1]/preceding::button[2]</value>
      <webElementGuid>8e72c263-e0b4-4bb3-9a27-629865c59f5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/div/div[2]/div/span/button</value>
      <webElementGuid>65ceda84-1e0e-4f69-832c-3a7e0b44d505</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'btnRecord' and @type = 'button' and (text() = ' Record Audio' or . = ' Record Audio')]</value>
      <webElementGuid>37d0a188-1827-4c47-bb9b-40dfb2d3b065</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
