<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Record1</name>
   <tag></tag>
   <elementGuidId>ba1a093a-1d05-4bca-b0db-5d405a50aaa2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@id='btnRecord'])[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f79c522a-5d23-4784-b913-189572d7fbce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btn-record</value>
      <webElementGuid>ee71df80-23e9-44dd-8201-a7624e252415</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnRecord</value>
      <webElementGuid>0e96c18c-7605-43ca-95fd-dabb5f8ce5c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Record And Playback 2 Record Audio</value>
      <webElementGuid>4fbf00cd-e204-4eb3-bdf6-e78210b30146</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-recording-id</name>
      <type>Main</type>
      <value>K9rs1ANi</value>
      <webElementGuid>d408b114-e20d-49ee-9d3f-fd9e8adafec4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-allow-retry</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>d9067220-8033-46b0-9cfe-dea61937c56b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-timer</name>
      <type>Main</type>
      <value>60</value>
      <webElementGuid>89e13f73-de30-47f3-9481-310bd7c157ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d4ad614e-247a-49d8-abf0-e8c398a73cf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Record Audio</value>
      <webElementGuid>573436fe-1ef0-4d81-87ac-67b124efd65c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dragAndDropMainPanel&quot;)/div[@class=&quot;grid-stack-item-content le-panel grid-stack-item ui-draggable ui-resizable ui-resizable-autohide ui-draggable-disabled ui-resizable-disabled&quot;]/div[1]/div[@class=&quot;le-widget ae-widget preview-widget&quot;]/div[@class=&quot;ibox float-e-margins&quot;]/div[@class=&quot;ibox-content&quot;]/div[@class=&quot;recorder-container list-question rclick-copy-area&quot;]/div[@class=&quot;ibox float-e-margins&quot;]/div[@class=&quot;recorder-container list-question ae-widget-wrap ibox question panel-suppressed-off&quot;]/div[@class=&quot;ae-content p-sm ibox-content panel-suppressed-off&quot;]/div[@class=&quot;recorder-main-control p-h-sm m-b&quot;]/span[1]/button[@id=&quot;btnRecord&quot;]</value>
      <webElementGuid>5f840db0-9caf-43af-98ca-ba1de6bae9bc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@id='btnRecord'])[2]</value>
      <webElementGuid>9ec35d1a-51fc-4db8-88dd-bb0c209f5f54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dragAndDropMainPanel']/div/div/div[2]/div/div/div[2]/div/div/div[2]/div/span/button</value>
      <webElementGuid>7478746a-dfe9-4ea3-8781-b93281c75a66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Record and Playback'])[2]/following::button[1]</value>
      <webElementGuid>4662cfec-d6dc-47a4-a662-7d959de0b0ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submit'])[1]/following::button[1]</value>
      <webElementGuid>a020513e-1c80-405c-ae34-9d41af6caccb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submit'])[2]/preceding::button[1]</value>
      <webElementGuid>893e54d2-f6dd-4f61-b033-169e25cef1e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Next'])[1]/preceding::button[2]</value>
      <webElementGuid>00523453-5dcd-4c95-92c1-bde612dee640</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/div/div[2]/div/span/button</value>
      <webElementGuid>53bd2d11-5e69-48bf-9812-dee4062a1cf9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'btnRecord' and @type = 'button' and (text() = ' Record Audio' or . = ' Record Audio')]</value>
      <webElementGuid>c64d5b49-c769-4fa5-9059-6688d0e17c41</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
