<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Submit2</name>
   <tag></tag>
   <elementGuidId>544c2d0b-e54d-4f90-8c6e-e464980e7bb6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@name='checkAnswerButton'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1a74e4ad-b34b-4b1a-a2b2-8a3f1cb2590e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary practiceButton</value>
      <webElementGuid>f395268e-a92c-481e-802f-427ee00d9dc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>checkAnswerButton</value>
      <webElementGuid>9ec28295-f63c-4ee4-b10f-8a5bd21c9ea3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Please select an answer!</value>
      <webElementGuid>51705cf8-42ae-42d0-9e16-520a98abfe25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Submit</value>
      <webElementGuid>70322d91-8e8d-4509-b2fa-a1c873149420</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dragAndDropMainPanel&quot;)/div[@class=&quot;grid-stack-item-content le-panel grid-stack-item ui-draggable ui-resizable ui-resizable-autohide ui-draggable-disabled ui-resizable-disabled&quot;]/div[1]/div[@class=&quot;le-widget preview-widget ae-widget&quot;]/div[@class=&quot;ibox float-e-margins&quot;]/div[@class=&quot;ibox-content&quot;]/div[@class=&quot;multiple-choice-control&quot;]/button[@class=&quot;btn btn-primary practiceButton&quot;]</value>
      <webElementGuid>e2a280aa-809c-4da5-b228-62c6630598f6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@name='checkAnswerButton'])[2]</value>
      <webElementGuid>ec5e4122-3894-41a8-bfdd-a3038301c3e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dragAndDropMainPanel']/div/div/div[2]/div/div/div[3]/button</value>
      <webElementGuid>637948a3-cf40-49d3-b82b-c6b93ecd2daf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Incorrect answer'])[6]/following::button[1]</value>
      <webElementGuid>78cf8475-b8d0-40b5-af7a-c91de49aa0c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Correct answer'])[6]/following::button[1]</value>
      <webElementGuid>4d0d2655-6ca5-424d-9ee7-539701c4ec8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Retry'])[2]/preceding::button[1]</value>
      <webElementGuid>7aff6093-4d3f-4264-a629-2a46f3b8fd0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Return to Video'])[2]/preceding::button[2]</value>
      <webElementGuid>25111002-6e71-4fb0-8d61-dd7f18e2b499</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[3]/button</value>
      <webElementGuid>fcbba728-7896-4db8-9286-50c4203a36b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@name = 'checkAnswerButton' and @title = 'Please select an answer!' and (text() = 'Submit' or . = 'Submit')]</value>
      <webElementGuid>3946fab4-1ceb-4f18-9e21-fdd86b975083</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
