<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Stop1</name>
   <tag></tag>
   <elementGuidId>178a1e25-da99-4666-8b9b-1c0197261565</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btnRecord']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btnRecord</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>654aec88-a829-49d5-b27e-379ab2e6c2f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btn-record</value>
      <webElementGuid>8e2cb884-a80d-4c50-9404-1e4fd176b339</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnRecord</value>
      <webElementGuid>9a865304-688c-49ea-9d9c-593664b5723e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Record And Playback 1 Record Audio</value>
      <webElementGuid>b9f9a3bb-3f4c-42ac-9f66-90163ec67274</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-recording-id</name>
      <type>Main</type>
      <value>xEOExC19</value>
      <webElementGuid>a50fec88-4752-449d-b631-a636c8d75dca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-allow-retry</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>c562abd0-9a66-4363-98f5-d1e1e880c4fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-timer</name>
      <type>Main</type>
      <value>25</value>
      <webElementGuid>47c5a8b9-e29b-48c2-ba69-04c2c9dc58e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d7febeb6-9c6a-40b3-9c47-33d844c66778</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Stop</value>
      <webElementGuid>bf0cb3e4-4fe4-475e-8af3-f4ef30006306</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dragAndDropMainPanel&quot;)/div[@class=&quot;grid-stack-item-content le-panel grid-stack-item ui-draggable ui-resizable ui-resizable-autohide ui-draggable-disabled ui-resizable-disabled&quot;]/div[1]/div[@class=&quot;le-widget ae-widget preview-widget&quot;]/div[@class=&quot;ibox float-e-margins&quot;]/div[@class=&quot;ibox-content&quot;]/div[@class=&quot;recorder-container list-question rclick-copy-area&quot;]/div[@class=&quot;ibox float-e-margins&quot;]/div[@class=&quot;recorder-container list-question ae-widget-wrap ibox question panel-suppressed-off&quot;]/div[@class=&quot;ae-content p-sm ibox-content panel-suppressed-off&quot;]/div[@class=&quot;recorder-main-control p-h-sm m-b&quot;]/span[1]/button[@id=&quot;btnRecord&quot;]</value>
      <webElementGuid>a65f28cf-4a21-4878-918a-ad147a3c6e9b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btnRecord']</value>
      <webElementGuid>f08e670c-128f-4303-a1d9-ce1a4638c831</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dragAndDropMainPanel']/div/div/div/div/div/div[2]/div/div/div[2]/div/span/button</value>
      <webElementGuid>12fb2e29-3dde-411f-87ce-999f6fc01da2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Record and Playback'])[1]/following::button[1]</value>
      <webElementGuid>821c9bfa-4b5a-4411-87c7-09ece794cf75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submit'])[1]/preceding::button[1]</value>
      <webElementGuid>94c5624d-c714-4c75-92e0-5f35f15d06d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Record and Playback'])[2]/preceding::button[2]</value>
      <webElementGuid>788b58c2-2ad8-4dc8-a18a-e27d15206327</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Stop']/parent::*</value>
      <webElementGuid>4e3b43b6-2d7b-445a-a938-62394d833a6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>413ee59d-a12f-417e-8e32-9a97c154e758</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'btnRecord' and @type = 'button' and (text() = ' Stop' or . = ' Stop')]</value>
      <webElementGuid>4fe0c537-9f1c-43bf-b606-5f631df87b8e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
