<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_mcm1</name>
   <tag></tag>
   <elementGuidId>0afd921b-c964-4681-896e-f7f8a93557fc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='lesson-answer-24508-61189']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#lesson-answer-24508-61189</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>607fe48a-6510-40b6-916b-37f954c65c38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>52b1f12f-2f97-4e6b-94e8-38d1c1dbd695</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>lesson-answer-checkbox-24508</value>
      <webElementGuid>9dd2e20b-82f5-4816-9f83-7ceb146a987c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>61189</value>
      <webElementGuid>0dc2a3d6-b423-4bee-874e-e1d0c1416daf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lesson-answer-24508-61189</value>
      <webElementGuid>6859ae63-7a54-474d-9139-e373f79ce732</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-expected-answer</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>10781a30-e56b-416d-86da-6255ee68effd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lesson-answer-24508-61189&quot;)</value>
      <webElementGuid>12b5f1ab-280c-41a3-bf03-fe9c262950f0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='lesson-answer-24508-61189']</value>
      <webElementGuid>0e6621ec-fde2-4249-a581-469a72eb86af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dragAndDropMainPanel']/div/div/div/div/div/div[2]/div/fieldset/div[2]/div/div/input</value>
      <webElementGuid>63b6ce43-4a18-4fb5-be9d-66cb3babb6a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/input</value>
      <webElementGuid>93f1b0ad-d24f-42f6-ba47-eaf3eeffabaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'lesson-answer-checkbox-24508' and @id = 'lesson-answer-24508-61189']</value>
      <webElementGuid>2f048efa-14cc-4567-9196-016ed74510c8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
