<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_sa2</name>
   <tag></tag>
   <elementGuidId>70042956-2362-48b3-a361-bb5bc9a26df2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='lesson-answer-text-24515']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#lesson-answer-text-24515</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>01c5ab9c-b691-4bd3-88b3-b079c65b198c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7584cf22-caf5-4f1b-b965-87abcde77b80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>lesson-answer-text-24515-0</value>
      <webElementGuid>17715f3f-c465-49a0-9308-698225b25e71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-question-id</name>
      <type>Main</type>
      <value>24515</value>
      <webElementGuid>4738fd86-f595-4500-a29d-8708b1668a6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-answer-id</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>9348b710-ee07-41c0-99c1-eeba51859802</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lesson-answer-text-24515</value>
      <webElementGuid>57715d4c-ea3c-4395-b883-5674f17f8fb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control question-answer-text</value>
      <webElementGuid>7d981552-8116-4a83-964f-a21d8c5b0e3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lesson-answer-text-24515&quot;)</value>
      <webElementGuid>3f9d213e-4088-43a6-a228-2aca8a31a978</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='lesson-answer-text-24515']</value>
      <webElementGuid>4977d6d4-6e88-4c36-888c-100579749904</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dragAndDropMainPanel']/div/div/div/div/div/div[2]/div[2]/div[2]/div[2]/div/div/span/input</value>
      <webElementGuid>92d32bd7-f99b-42d7-9fe4-508ea092e79d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[2]/div/div/span/input</value>
      <webElementGuid>40221634-8488-496f-9910-4fa5019644df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'lesson-answer-text-24515-0' and @id = 'lesson-answer-text-24515']</value>
      <webElementGuid>bf575ae2-7690-4c3d-b3b9-74d14022017b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
