<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_mc1</name>
   <tag></tag>
   <elementGuidId>73a9bbbc-4cf3-4450-a1e7-50bc57ed8de6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='lesson-answer-24505-61183']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#lesson-answer-24505-61183</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a33a9295-1657-4e12-b442-f239467fa13a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>c887338c-ff7d-4084-abbe-48440ada4012</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>lesson-answer-radio-24505</value>
      <webElementGuid>390152e1-c31d-406f-9379-5254a3da2fce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>61183</value>
      <webElementGuid>b6f2268b-4a90-44fc-92d9-a34232db187c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lesson-answer-24505-61183</value>
      <webElementGuid>6d0f0ee3-05ff-4541-9761-9bf8a2b21193</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lesson-answer-24505-61183&quot;)</value>
      <webElementGuid>e7d41237-35d2-4f05-a559-b6bce2d78e59</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='lesson-answer-24505-61183']</value>
      <webElementGuid>db1dfdeb-93a7-4f32-ad95-1c4ff53e6cb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dragAndDropMainPanel']/div/div/div/div/div/div[2]/div/fieldset/div[2]/div/div/input</value>
      <webElementGuid>d4df149f-81e4-4268-9966-595b1ffe72db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/input</value>
      <webElementGuid>226c0e32-8a12-4b70-9c71-5d18234d5e9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'lesson-answer-radio-24505' and @id = 'lesson-answer-24505-61183']</value>
      <webElementGuid>cf6c5a17-3f27-4a31-960e-ba301edb8cd8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
