<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ce4</name>
   <tag></tag>
   <elementGuidId>b2fe8c72-6443-4135-9067-dcc53b3bc3a0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='lesson-answer-24504-61181']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#lesson-answer-24504-61181</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>54fb0f5d-df54-45a6-83e2-9d212cc5950c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>70d0bf4a-bf7f-45c4-a0d3-6d354253886b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>lesson-answer-checkbox-24504</value>
      <webElementGuid>89032563-a4fd-47fd-8430-ce88bce177c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>61181</value>
      <webElementGuid>5d9b3f35-2343-4741-b86f-6ec078d53e13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lesson-answer-24504-61181</value>
      <webElementGuid>ddd69938-d218-4ca6-ad5f-22754031db8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lesson-answer-24504-61181&quot;)</value>
      <webElementGuid>a27a2ae5-e945-4c5c-833c-a48b856f1909</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='lesson-answer-24504-61181']</value>
      <webElementGuid>9c70f606-bdf6-422c-9f10-9cabc8544aaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dragAndDropMainPanel']/div/div/div[2]/div/div/div[2]/div[2]/fieldset/div[2]/div[2]/div/input</value>
      <webElementGuid>0eca90f2-e8f3-466a-a5a5-2d036f1c072f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/fieldset/div[2]/div[2]/div/input</value>
      <webElementGuid>caa15cd0-753f-4bd0-9898-44347386de1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'lesson-answer-checkbox-24504' and @id = 'lesson-answer-24504-61181']</value>
      <webElementGuid>8a590baf-7da4-45d0-9552-f11b7c6842d2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
