<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ce2</name>
   <tag></tag>
   <elementGuidId>86760c53-6a72-4267-a923-fe810baa40e0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='lesson-answer-24503-61177']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#lesson-answer-24503-61177</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d2c5f36e-da08-4b5d-8404-1101268e5f11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>58e5a7a1-54f3-4e52-be41-78f0481a8d0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>lesson-answer-checkbox-24503</value>
      <webElementGuid>8b87ac02-dea9-4aa0-931a-f42e839d927c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>61177</value>
      <webElementGuid>454ba02c-992d-4a2f-b6cc-af5abf843895</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lesson-answer-24503-61177</value>
      <webElementGuid>08b463ab-4377-4b4c-a0b1-7d56757b3ef5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lesson-answer-24503-61177&quot;)</value>
      <webElementGuid>a4131f07-cc2f-4be4-b0fa-5b5142e68cc3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='lesson-answer-24503-61177']</value>
      <webElementGuid>81cec767-458b-4976-935d-d5ca33d37be7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dragAndDropMainPanel']/div/div/div[2]/div/div/div[2]/div/fieldset/div[2]/div/div/input</value>
      <webElementGuid>ace5b5c6-54d6-4c75-8610-8833fbd5be97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/fieldset/div[2]/div/div/input</value>
      <webElementGuid>0913937b-27ec-4870-9e54-3b50c34ce214</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'lesson-answer-checkbox-24503' and @id = 'lesson-answer-24503-61177']</value>
      <webElementGuid>7405dcfe-d9a9-4c97-a3f1-ecf8c100c3fc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
