<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_mcm4</name>
   <tag></tag>
   <elementGuidId>dc8b8782-19f5-40c7-b39d-ee55da4798ea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='lesson-answer-24510-61193']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#lesson-answer-24510-61193</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6cfeafd8-c8d1-4d95-8f46-e5110ada948a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>e6713aa5-7f33-42ba-891d-ac658e7aa5d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>lesson-answer-checkbox-24510</value>
      <webElementGuid>1fb70e4d-b7b7-41fe-b78d-e410ffdcb605</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>61193</value>
      <webElementGuid>b58e2f93-8520-486f-910d-edb48edc53c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lesson-answer-24510-61193</value>
      <webElementGuid>d16c7ff1-baa7-4248-88f0-1b7731420d8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-expected-answer</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>63b52763-5b47-4891-8adb-83edfd861817</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lesson-answer-24510-61193&quot;)</value>
      <webElementGuid>3e15225d-5cfb-4ef9-a707-8b58b96e6e5d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='lesson-answer-24510-61193']</value>
      <webElementGuid>ad29e119-c35f-4f23-9e94-c8ff44b96c1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dragAndDropMainPanel']/div/div/div[2]/div/div/div[2]/div/fieldset/div[2]/div/div/input</value>
      <webElementGuid>a249e7ea-12a7-4738-b111-3306432cc890</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/fieldset/div[2]/div/div/input</value>
      <webElementGuid>d51f1792-95f8-4f4c-a184-6637f1fb6330</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'lesson-answer-checkbox-24510' and @id = 'lesson-answer-24510-61193']</value>
      <webElementGuid>64033f74-36d8-4376-a2dd-71e84ec40a9b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
