<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_mc3</name>
   <tag></tag>
   <elementGuidId>562ec5f6-9ddf-4d89-a25c-8a299e03cc25</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='lesson-answer-24507-61187']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#lesson-answer-24507-61187</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c96615ae-eafd-4dff-be99-cb2faaab34cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>77a10da5-dcc6-4d93-a3a6-5cbef1d56396</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>lesson-answer-radio-24507</value>
      <webElementGuid>dda9e134-1802-4145-9d57-d582b231e2c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>61187</value>
      <webElementGuid>b5b29261-19bf-477c-af83-71580a551f4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lesson-answer-24507-61187</value>
      <webElementGuid>162f4539-d8cd-4fc8-b50d-3d7d91f8c073</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lesson-answer-24507-61187&quot;)</value>
      <webElementGuid>e16290c3-8a31-4acf-86f2-bc903691683c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='lesson-answer-24507-61187']</value>
      <webElementGuid>552e7497-c2c8-4520-9778-2a718f9ef603</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dragAndDropMainPanel']/div/div/div[2]/div/div/div[2]/div/fieldset/div[2]/div/div/input</value>
      <webElementGuid>8100c1b0-3746-4416-b2c5-2938d2c855bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/fieldset/div[2]/div/div/input</value>
      <webElementGuid>29df5d8c-daab-40b1-933b-651cdabe2cfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'lesson-answer-radio-24507' and @id = 'lesson-answer-24507-61187']</value>
      <webElementGuid>0f0645d2-ec14-48b3-bd93-e6f4ffbb9913</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
