<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_sa3</name>
   <tag></tag>
   <elementGuidId>78fbe8a3-ebe0-404c-82c8-c0d09b233d5a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='lesson-answer-text-24516']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#lesson-answer-text-24516</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c2457955-fd4e-4356-b7c2-7a871921d011</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>82e5069e-26aa-4205-ab18-0d44c522f19a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>lesson-answer-text-24516-0</value>
      <webElementGuid>4e4a5da0-4508-468a-aa0e-4e32258b58a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-question-id</name>
      <type>Main</type>
      <value>24516</value>
      <webElementGuid>7ca57e8e-b9b5-4818-b34d-5eb3bf9e4563</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-answer-id</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>cd8925cd-5c55-48fa-98a6-70333f09aac4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lesson-answer-text-24516</value>
      <webElementGuid>cd8dd736-4466-4084-a1fb-15fed5a0f8b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control question-answer-text</value>
      <webElementGuid>af059e75-bc54-4f96-806d-b0f7a389e299</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lesson-answer-text-24516&quot;)</value>
      <webElementGuid>b4179607-df66-41d4-814e-2ff15fbcf871</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='lesson-answer-text-24516']</value>
      <webElementGuid>c05096cc-9d95-4dee-b62d-1ae2c248fad1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dragAndDropMainPanel']/div/div/div[2]/div/div/div[2]/div/div[2]/div[2]/div/div/span/input</value>
      <webElementGuid>6991e356-2f9e-4af6-81cb-c3ce4e49fda6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/div[2]/div[2]/div/div/span/input</value>
      <webElementGuid>80d8bd36-15ba-4e24-b207-f051a5a8bd00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'lesson-answer-text-24516-0' and @id = 'lesson-answer-text-24516']</value>
      <webElementGuid>ab1648dd-ab6a-41be-8b79-e0cd6985b7c5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
