<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_cca2</name>
   <tag></tag>
   <elementGuidId>782dfcde-3cd3-4b3a-a2c0-8702dfcc545b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='lesson-answer-24512-61197']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#lesson-answer-24512-61197</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>79570b54-7e49-4ce7-b20f-9737350a5dc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>c22a9296-ce90-4016-9387-729d46066c93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>lesson-answer-radio-24512</value>
      <webElementGuid>7a7c023a-ab5d-47c7-9ce8-325b03556618</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>61197</value>
      <webElementGuid>72897437-f139-40b0-b574-82c976630b83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lesson-answer-24512-61197</value>
      <webElementGuid>3c521487-42e4-429c-8e1b-b580085c5be9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lesson-answer-24512-61197&quot;)</value>
      <webElementGuid>47c95ed5-9a4b-4b1a-bea1-da3d13174522</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='lesson-answer-24512-61197']</value>
      <webElementGuid>4dcf945f-67f9-4fd9-a833-6c176a14680d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dragAndDropMainPanel']/div/div/div/div/div/div[2]/div[2]/fieldset/div[2]/div/label/input</value>
      <webElementGuid>13e67b13-cacc-4981-a9a8-63689e146d0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/fieldset/div[2]/div/label/input</value>
      <webElementGuid>f495460b-a12b-4dfd-bd17-229264caebf7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'lesson-answer-radio-24512' and @id = 'lesson-answer-24512-61197']</value>
      <webElementGuid>c1bc12af-68ac-458e-af25-d0c631b7f08b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
