<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_cca1</name>
   <tag></tag>
   <elementGuidId>cc0592fb-c04c-4239-8b38-3c60844cf160</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='lesson-answer-24511-61195']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#lesson-answer-24511-61195</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d7764ae1-d35d-4409-a647-0ddc11058e4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>f222c584-9ea1-4b57-99c1-18f6d587fc9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>lesson-answer-radio-24511</value>
      <webElementGuid>65eadc29-a2f6-48a3-8181-314fac3d48cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>61195</value>
      <webElementGuid>1d8c9563-d293-4dcd-86ce-fa3b839569b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lesson-answer-24511-61195</value>
      <webElementGuid>5e1b5b0f-1b71-48ee-9ab4-0a5a85b0ed32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lesson-answer-24511-61195&quot;)</value>
      <webElementGuid>4db0a217-2789-494b-aa76-088c388a53c4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='lesson-answer-24511-61195']</value>
      <webElementGuid>ce2d8295-7650-4c33-a122-8f3a338eb898</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dragAndDropMainPanel']/div/div/div/div/div/div[2]/div/fieldset/div[2]/div/label/input</value>
      <webElementGuid>d0227970-a008-4339-a4c2-30ef16eae4df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/input</value>
      <webElementGuid>d671856a-3705-460c-abac-f935e88ec0f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'lesson-answer-radio-24511' and @id = 'lesson-answer-24511-61195']</value>
      <webElementGuid>bcdc7686-b239-4ed6-a9b8-79f773f6248f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
