<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_sa4</name>
   <tag></tag>
   <elementGuidId>d1937dd9-3f03-4a59-8dcf-7a1aa9af41fa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='lesson-answer-text-24517']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#lesson-answer-text-24517</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a68d2b83-6883-44e9-99c0-9fb493bc2077</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5a18b465-a89c-4f02-a02e-24ec1eed17fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>lesson-answer-text-24517-0</value>
      <webElementGuid>ccddf058-b2b7-42b2-a96f-4050a420b773</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-question-id</name>
      <type>Main</type>
      <value>24517</value>
      <webElementGuid>3fb2bb82-aeec-4dc2-a7d6-da448c668fa4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-answer-id</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>63343b8a-5d31-4082-926f-d211af85da35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lesson-answer-text-24517</value>
      <webElementGuid>10f07959-94d3-4c09-8ea3-0e3043f2fda7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control question-answer-text</value>
      <webElementGuid>d40607f7-4a4a-49aa-9198-fb198341d5dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lesson-answer-text-24517&quot;)</value>
      <webElementGuid>37b0b22f-d7c1-4a90-8e35-e85d534be626</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='lesson-answer-text-24517']</value>
      <webElementGuid>7fb4252b-4bf3-4b25-accb-5f8b2c240a08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dragAndDropMainPanel']/div/div/div[2]/div/div/div[2]/div[2]/div[2]/div[2]/div/div/span/input</value>
      <webElementGuid>e8cd2ec0-4456-402e-a807-90d8fec0a22f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div[2]/div[2]/div[2]/div/div/span/input</value>
      <webElementGuid>6a2b4168-e9b0-456e-ace5-6cd54e43b48c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'lesson-answer-text-24517-0' and @id = 'lesson-answer-text-24517']</value>
      <webElementGuid>9900905f-b25e-4734-b818-9049a65b4483</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
