<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_mcm2</name>
   <tag></tag>
   <elementGuidId>6c87f4d4-df85-40b4-8b41-c74669eb4986</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='lesson-answer-24509-61191']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#lesson-answer-24509-61191</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6f414db2-7109-4747-90c0-bae7b8ee9677</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>3fd7afa1-2eca-4cc8-9783-a01142d4c53b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>lesson-answer-checkbox-24509</value>
      <webElementGuid>58f219b8-43e2-4e6f-a4cb-20cd78110efa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>61191</value>
      <webElementGuid>e9ed5575-b09c-471d-b998-dcf09dd95679</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lesson-answer-24509-61191</value>
      <webElementGuid>49535b43-f277-421c-b3d2-00af4f2b314e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-expected-answer</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>fc2a5edc-db06-4bf1-b36c-f592537cd9a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lesson-answer-24509-61191&quot;)</value>
      <webElementGuid>baf54e94-876d-426c-85d0-3425ca96814c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='lesson-answer-24509-61191']</value>
      <webElementGuid>685ffd4d-0eb4-41ab-9f4c-24d969648f85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dragAndDropMainPanel']/div/div/div/div/div/div[2]/div[2]/fieldset/div[2]/div/div/input</value>
      <webElementGuid>ec47ed83-5ee2-43df-9e65-4e03f67b7f0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/fieldset/div[2]/div/div/input</value>
      <webElementGuid>75c33223-78f3-462a-b3b3-d6b15319910b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'lesson-answer-checkbox-24509' and @id = 'lesson-answer-24509-61191']</value>
      <webElementGuid>a0342b4f-941a-4f0a-a248-332bafa2683d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
