<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_cca3</name>
   <tag></tag>
   <elementGuidId>c20037c0-915a-45b9-8a76-80aef9cdff63</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='lesson-answer-24513-61199']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#lesson-answer-24513-61199</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1aeffdc9-9445-4aac-b8f7-ea55bc42d6cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>6e0172b8-7b84-44b6-bf63-9516c4971ddc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>lesson-answer-radio-24513</value>
      <webElementGuid>e3aad9c8-461f-4b1e-a6d0-0cb9148e2875</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>61199</value>
      <webElementGuid>4f6de26a-a6ae-423b-a47a-853073d4bc68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lesson-answer-24513-61199</value>
      <webElementGuid>c9438323-264b-48a5-824f-87e6dffd4dfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lesson-answer-24513-61199&quot;)</value>
      <webElementGuid>c3454919-a5d0-4028-ba8a-a038d4cc4d4f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='lesson-answer-24513-61199']</value>
      <webElementGuid>209704ef-b0b8-410c-84fb-742ce59349fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dragAndDropMainPanel']/div/div/div[2]/div/div/div[2]/div/fieldset/div[2]/div/label/input</value>
      <webElementGuid>3759b44c-647a-428d-819c-e233195afa2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/fieldset/div[2]/div/label/input</value>
      <webElementGuid>a857ba15-0255-479a-b076-e64b71d246ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'lesson-answer-radio-24513' and @id = 'lesson-answer-24513-61199']</value>
      <webElementGuid>0c254856-d00c-4598-a8aa-1de76965698f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
