<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_mc2</name>
   <tag></tag>
   <elementGuidId>1732b3cb-2925-4c82-87b8-916420f79320</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='lesson-answer-24506-61185']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#lesson-answer-24506-61185</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5b167279-0961-4928-9336-d8cf7fabc621</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>4b099c46-3dcd-4ac5-9dc5-4baf527b8d96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>lesson-answer-radio-24506</value>
      <webElementGuid>f5804261-494a-4da6-a55e-5c011d9f018e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>61185</value>
      <webElementGuid>2228cbb1-bac6-4855-a50d-b7e0fa6c6c12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lesson-answer-24506-61185</value>
      <webElementGuid>a1e4ab5e-0e8c-44aa-9491-3e0e1cf548c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lesson-answer-24506-61185&quot;)</value>
      <webElementGuid>4567ddd1-0c54-4927-9611-dcf540ef84bf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='lesson-answer-24506-61185']</value>
      <webElementGuid>58e032f8-de4f-4718-99d5-d4ae2c7b04d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dragAndDropMainPanel']/div/div/div/div/div/div[2]/div[2]/fieldset/div[2]/div/div/input</value>
      <webElementGuid>e8e93590-e8ed-4bb4-ad48-d3baa5528ca3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/fieldset/div[2]/div/div/input</value>
      <webElementGuid>8460fce6-8782-42a3-bc2d-70f72cc68796</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'lesson-answer-radio-24506' and @id = 'lesson-answer-24506-61185']</value>
      <webElementGuid>2920411d-b4bb-4097-85b5-7f4812cdb933</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
