<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_sa1</name>
   <tag></tag>
   <elementGuidId>8394dcb2-2f60-433e-bcba-9c4da0801759</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='lesson-answer-text-24514']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#lesson-answer-text-24514</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>27348d4e-7f37-4ca7-9e92-a6ae41b8b4dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1b64aaba-ce9a-4ede-b8b8-673265af036f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>lesson-answer-text-24514-0</value>
      <webElementGuid>86f3d245-4759-46c1-95a4-f5d48b7b445b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-question-id</name>
      <type>Main</type>
      <value>24514</value>
      <webElementGuid>ce7ca861-877b-413b-b11f-e56e2bac7edd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-answer-id</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>b109b52f-f46d-49c5-ad26-73f934e05caa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lesson-answer-text-24514</value>
      <webElementGuid>7c146e7f-8c40-40a1-b848-26b7eb31f25c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control question-answer-text</value>
      <webElementGuid>970800e4-174a-4672-b299-e040b8df2449</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lesson-answer-text-24514&quot;)</value>
      <webElementGuid>78c68f56-48d9-49af-bfec-e94ce160b9b2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='lesson-answer-text-24514']</value>
      <webElementGuid>93cb1a75-0620-48c8-99c5-b1b7fa74f7c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dragAndDropMainPanel']/div/div/div/div/div/div[2]/div/div[2]/div[2]/div/div/span/input</value>
      <webElementGuid>507cc2b8-7af8-4d8b-9ac9-c634a7d94e09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/input</value>
      <webElementGuid>52936596-cc6a-40c6-9392-742ab87b69be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'lesson-answer-text-24514-0' and @id = 'lesson-answer-text-24514']</value>
      <webElementGuid>ba5cdba1-d139-4faf-977c-8e1dbff01e09</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
