<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_mcm3</name>
   <tag></tag>
   <elementGuidId>f54e96ee-b395-4eac-a25d-d324942baf80</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='lesson-answer-24509-61192']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#lesson-answer-24509-61192</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f681b89c-e983-40a1-90ab-aa0605db404a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>58914ef0-bffb-4984-8634-4e72d6140b06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>lesson-answer-checkbox-24509</value>
      <webElementGuid>184f3962-33fe-4c11-a51d-5e26c0a6991d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>61192</value>
      <webElementGuid>346ea555-aa47-4355-a4d8-3b4a8ebd3004</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lesson-answer-24509-61192</value>
      <webElementGuid>8077ecfb-f8f2-4963-9d1d-067208a101b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lesson-answer-24509-61192&quot;)</value>
      <webElementGuid>e2139863-2901-445d-9d23-3991de5901f2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='lesson-answer-24509-61192']</value>
      <webElementGuid>43bec32a-48d7-47a0-8f92-f3c7008a9fc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dragAndDropMainPanel']/div/div/div/div/div/div[2]/div[2]/fieldset/div[2]/div[2]/div/input</value>
      <webElementGuid>857e3e80-c1fd-4af9-b6c5-2a508ec38b57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/fieldset/div[2]/div[2]/div/input</value>
      <webElementGuid>a1fb34a6-1fff-4841-becb-ff604d92d3de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'lesson-answer-checkbox-24509' and @id = 'lesson-answer-24509-61192']</value>
      <webElementGuid>489d7b34-0e99-4373-94db-30093df669ef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
