<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ce3</name>
   <tag></tag>
   <elementGuidId>eeaea8e0-bcbf-4256-bfbf-bb4856332bfd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='lesson-answer-24504-61180']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#lesson-answer-24504-61180</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2ceca409-4d4e-4354-8a20-adf5356f4dd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>81742897-59dc-46c5-b611-cdf8fe733e2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>lesson-answer-checkbox-24504</value>
      <webElementGuid>bac14b1f-d111-4de2-926e-dd9ba46872ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>61180</value>
      <webElementGuid>d0c122e3-9a20-4769-aa69-431bfac0abfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lesson-answer-24504-61180</value>
      <webElementGuid>effe461c-963c-473a-8bbd-d3d9ab3d3158</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lesson-answer-24504-61180&quot;)</value>
      <webElementGuid>f960ff23-5bc7-4e55-bc0b-c12ddfc7201c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='lesson-answer-24504-61180']</value>
      <webElementGuid>715609ff-0fb8-4186-9399-b137bed46344</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dragAndDropMainPanel']/div/div/div[2]/div/div/div[2]/div[2]/fieldset/div[2]/div/div/input</value>
      <webElementGuid>bb4601f8-09cf-4bff-bd0a-5d667166d63a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/fieldset/div[2]/div/div/input</value>
      <webElementGuid>1207f304-aa28-43ea-859c-c770abe82690</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'lesson-answer-checkbox-24504' and @id = 'lesson-answer-24504-61180']</value>
      <webElementGuid>50a32382-acf5-433d-b1e1-c7c1fbd2fcaa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
