<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ce1</name>
   <tag></tag>
   <elementGuidId>34db3c04-6005-45f8-a84d-ac38dde14b28</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='lesson-answer-24502-61175']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#lesson-answer-24502-61175</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>898fb908-fdd7-45d1-ac1a-1a85279b5fd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>d11c1085-c74f-4fc1-8b5d-1062c266ce83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>lesson-answer-checkbox-24502</value>
      <webElementGuid>bcd2335e-cc8e-4f19-9039-ff54617b7c06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>61175</value>
      <webElementGuid>cf8770ed-4356-4914-ab55-7f3a8c42643d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lesson-answer-24502-61175</value>
      <webElementGuid>8b39fb2d-160d-452e-907d-40d589c7f1a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lesson-answer-24502-61175&quot;)</value>
      <webElementGuid>40ddc89f-ae30-4b1b-b722-0f17ec897388</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='lesson-answer-24502-61175']</value>
      <webElementGuid>82c8bf4a-b047-4e8d-914d-917d9cd039b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dragAndDropMainPanel']/div/div/div/div/div/div[2]/div/fieldset/div[2]/div/div/input</value>
      <webElementGuid>b427372e-d305-4b17-9738-942d1b326fbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/input</value>
      <webElementGuid>60eb8199-df45-4b31-8f45-1afbf99ab811</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'lesson-answer-checkbox-24502' and @id = 'lesson-answer-24502-61175']</value>
      <webElementGuid>3c53105c-6f93-4c51-96b8-27a926e51bd0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
