<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_cca3</name>
   <tag></tag>
   <elementGuidId>8b1a24f8-0c47-4159-9878-88deb2cc6165</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='dd-custom-answer-group-11621'][3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#dd-custom-answer-group-11621</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>995fee3c-31d3-4dd4-abb8-610d86a6bbb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dd-custom-answer-group-11621</value>
      <webElementGuid>201aa668-4b12-43d0-a850-dd2432275ab7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dd-widget-select-selected</value>
      <webElementGuid>653e5998-d91f-4d38-b82d-0bf86f8a7683</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>- </value>
      <webElementGuid>a3908bc5-3bc5-4c08-9bc3-5a036a2e2507</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dd-custom-answer-group-11621&quot;)</value>
      <webElementGuid>2db7c322-f60f-426f-9dc4-e8732f12a3b4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='dd-custom-answer-group-11621']</value>
      <webElementGuid>b88c1d8d-dcf5-4253-b121-99bac3f56290</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dragAndDropMainPanel']/div/div/div/div/fieldset/form/div[4]/fieldset/div/span/span</value>
      <webElementGuid>bb868c3a-40bd-41db-a08f-ee5c13c615b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[2]/following::span[6]</value>
      <webElementGuid>bd569a55-dade-4dcf-bd40-fdf405530e9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submit'])[1]/preceding::span[5]</value>
      <webElementGuid>9642ace4-38c8-433f-8000-c46c0de11172</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Retry'])[1]/preceding::span[5]</value>
      <webElementGuid>90625eee-4efb-4f4f-bd1e-a030b346ce76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/fieldset/div/span/span</value>
      <webElementGuid>ba3ad675-731c-4370-8dd4-b27bbf9381a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'dd-custom-answer-group-11621' and (text() = '- ' or . = '- ')]</value>
      <webElementGuid>bdb46151-893d-4e6b-a9fd-ea06bc59dba6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
