<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_cca1</name>
   <tag></tag>
   <elementGuidId>0d890046-c717-4b96-99f2-74aa52b9b7a5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='dd-custom-answer-group-11621'][1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#dd-custom-answer-group-11621</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>84719c28-0972-4426-9966-3d255fc5c660</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dd-custom-answer-group-11621</value>
      <webElementGuid>ab217ce7-385e-4c72-b963-e5688604023f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dd-widget-select-selected</value>
      <webElementGuid>2e958b83-4a16-45f4-a5ac-c3051e6d885e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>- </value>
      <webElementGuid>bebd086a-7c7a-4151-9606-13c4f3de261d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dd-custom-answer-group-11621&quot;)</value>
      <webElementGuid>c373c00d-5514-4649-b45b-0bd633257e78</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='dd-custom-answer-group-11621']</value>
      <webElementGuid>c773a82b-dd74-4a14-ab8b-e3e2bc7fd571</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dragAndDropMainPanel']/div/div/div/div/fieldset/form/div[4]/fieldset/div/span/span</value>
      <webElementGuid>23fe1236-beda-40cf-a679-237b62dcbd3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[2]/following::span[6]</value>
      <webElementGuid>32514bc1-8d34-49f0-b94d-b58ba85c6ad3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submit'])[1]/preceding::span[5]</value>
      <webElementGuid>9925d176-3330-4ef6-b0a4-fbf911735c24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Retry'])[1]/preceding::span[5]</value>
      <webElementGuid>27fe9038-5e5c-4785-a53f-31278f343d1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/fieldset/div/span/span</value>
      <webElementGuid>781a67da-e89a-4eed-afbe-1a5a99b0d2c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'dd-custom-answer-group-11621' and (text() = '- ' or . = '- ')]</value>
      <webElementGuid>8029d10e-e0a7-4882-86d5-25281cce6b6f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
