<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_cca2</name>
   <tag></tag>
   <elementGuidId>e7bd6449-fd08-48fe-b0c5-1c151c37a825</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='dd-custom-answer-group-11621'][2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#dd-custom-answer-group-11621</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>5c610bc6-126f-4e60-a1d5-7eb529fe713d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dd-custom-answer-group-11621</value>
      <webElementGuid>d053eb53-5ba3-4dce-97da-2e87f3f845bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dd-widget-select-selected</value>
      <webElementGuid>e3634ace-7a07-4289-b56a-5c054dd31fea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>- </value>
      <webElementGuid>2a5b56f6-d580-41eb-a3b3-3b7eeaae1c93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dd-custom-answer-group-11621&quot;)</value>
      <webElementGuid>6a403917-7577-4ffb-9bdb-4e259a537095</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='dd-custom-answer-group-11621']</value>
      <webElementGuid>d1ce724c-1798-4398-9f2a-f656cc103a74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dragAndDropMainPanel']/div/div/div/div/fieldset/form/div[4]/fieldset/div/span/span</value>
      <webElementGuid>bd667ffc-8a36-4aa7-a57a-42586a955d7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[2]/following::span[6]</value>
      <webElementGuid>7fb5b87e-d44a-418a-add6-8f3ff84b9aaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submit'])[1]/preceding::span[5]</value>
      <webElementGuid>5479329d-ba4a-4be1-bdff-7205e44b8691</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Retry'])[1]/preceding::span[5]</value>
      <webElementGuid>cde4d95d-00ee-444a-8a3d-922f159e9154</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/fieldset/div/span/span</value>
      <webElementGuid>0888379b-eb00-4a20-9c13-fff4d563134b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'dd-custom-answer-group-11621' and (text() = '- ' or . = '- ')]</value>
      <webElementGuid>7e5ec736-6f61-4520-b9ef-73faa950cfc1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
