<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_NEXT</name>
   <tag></tag>
   <elementGuidId>14e4ca56-eea2-4d65-b70c-c9df5817e1cf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='goToDashboardBtn']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#goToDashboardBtn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>47e351e5-d3a7-4743-9433-b3df14115c4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>ee41368e-15b7-4c8e-92b1-c16d8a2176fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3eaf237c-010b-4585-a8b5-08c204b40c79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>goToDashboardBtn</value>
      <webElementGuid>92d16bfa-3e38-456b-9dc2-7575725e32db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btn-xl width-full</value>
      <webElementGuid>759b17cd-9844-4827-a2e6-9fafda03b58d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>NEXT: GO TO THE DASHBOARD</value>
      <webElementGuid>56491795-639c-4617-ac61-e22508b34d20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;goToDashboardBtn&quot;)</value>
      <webElementGuid>03b3523b-5f74-4f8c-a19c-171e031a6eb4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='goToDashboardBtn']</value>
      <webElementGuid>e5182ff0-8cd8-4f0e-8a25-ed505ce6a197</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mainUserContent']/div/div[2]/div/div/div/div[3]/div/a</value>
      <webElementGuid>e61f68ab-70e4-4b67-82ef-6d5326eb11ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'NEXT: GO TO THE DASHBOARD')]</value>
      <webElementGuid>c3586399-5b8f-443d-8229-172e2cf8a528</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='This field is required.'])[2]/following::a[1]</value>
      <webElementGuid>99b2f2dc-213d-4bf0-8865-6354e362b801</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DON’T KNOW'])[1]/following::a[1]</value>
      <webElementGuid>0c02aa34-ca9d-407a-b1d1-90d292793a1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='START FREE TRIAL'])[1]/preceding::a[1]</value>
      <webElementGuid>98b325f3-30e3-443e-bb8e-6e0d2d3b4bce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Which course do you want to try?'])[1]/preceding::a[1]</value>
      <webElementGuid>40b25baa-1236-45bc-ae34-8b4011688c74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='NEXT: GO TO THE DASHBOARD']/parent::*</value>
      <webElementGuid>45ee4c49-3dd4-4674-80d7-55b03f507225</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[2]</value>
      <webElementGuid>c098a9e5-8db5-4542-9d5c-8d0950df7ecb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/a</value>
      <webElementGuid>47f92c74-6ec8-4900-ab55-4d7f3fdb8f1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and @id = 'goToDashboardBtn' and (text() = 'NEXT: GO TO THE DASHBOARD' or . = 'NEXT: GO TO THE DASHBOARD')]</value>
      <webElementGuid>3367989a-09ae-421e-83eb-c9811d7fef70</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
