<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Try for Free</name>
   <tag></tag>
   <elementGuidId>419c1e9c-0e2c-48b0-93a4-ef3357c98fdb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='tryAsFreeButton']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#tryAsFreeButton</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0ab47897-10a6-4914-8fae-4135caa81f0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tryAsFreeButton</value>
      <webElementGuid>07af138a-2c73-45b8-8f0f-cfaa65a3ca1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-lg btn-danger btn-block btn-prev</value>
      <webElementGuid>162dbafc-2b29-4947-be56-634b14256798</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/Registration?option=Free_0</value>
      <webElementGuid>53c01cea-50b7-465d-b8f6-cce86fa2e5e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                Try for Free!
                            </value>
      <webElementGuid>815a8106-99b6-457a-85a6-942a847bf102</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tryAsFreeButton&quot;)</value>
      <webElementGuid>2078b4ff-f9bb-4b85-bd2b-054ec06ea130</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3784c326-f5c1-4c5b-bd46-fbb48f5abb25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tryAsFreeButton</value>
      <webElementGuid>39297d05-3307-401f-8894-3256be8b2567</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-lg btn-danger btn-block btn-prev</value>
      <webElementGuid>c65cc196-4ff1-4d6f-b79f-d359fd701ad6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/Registration?option=Free_0</value>
      <webElementGuid>0f894747-1f05-49c5-9edc-7daf1e401012</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                Try for Free!
                            </value>
      <webElementGuid>7bfd39db-be3f-46b1-993a-c173b6df799d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tryAsFreeButton&quot;)</value>
      <webElementGuid>e21d28d3-16c8-428b-9036-80334e4c15a4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='tryAsFreeButton']</value>
      <webElementGuid>09cf01a6-9e6b-487f-845d-ba08db5bb0dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='registrationForm']/div[2]/div[3]/div/a</value>
      <webElementGuid>f8d99f9e-2cda-46bb-a3d5-1040ae9b355c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Try for Free!')]</value>
      <webElementGuid>449fc417-2951-4d2c-b0b1-822ef14378d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TOEIC'])[1]/following::a[1]</value>
      <webElementGuid>e8ccaf56-2934-47bf-8182-13207d2b0065</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CELPIP General LS'])[1]/following::a[1]</value>
      <webElementGuid>1c5d7168-d48f-4b93-8124-8f6a68e31c58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View Packages'])[1]/preceding::a[1]</value>
      <webElementGuid>96eec591-e1f5-40ca-9b23-5bb4bae56bf0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Try for Free!']/parent::*</value>
      <webElementGuid>b5d416cc-bd3e-4451-a1ab-6719f5492b08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/Registration?option=Free_0')]</value>
      <webElementGuid>89e3b468-62d2-408c-842e-bb787b2ac97d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/a</value>
      <webElementGuid>3b40221d-de3e-4f83-9024-b7ec0f2e1f7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'tryAsFreeButton' and @href = '/Registration?option=Free_0' and (text() = '
                                Try for Free!
                            ' or . = '
                                Try for Free!
                            ')]</value>
      <webElementGuid>48f52b15-9ea8-4d36-8547-f2818456ad99</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
