<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_View Packages</name>
   <tag></tag>
   <elementGuidId>448c0d91-be24-4808-b7c7-f485a82c3c14</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='signAsPaidButton']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#signAsPaidButton</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1be8daaa-1f33-4013-a9da-50df94d32269</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>signAsPaidButton</value>
      <webElementGuid>f37f3d67-df65-42b4-ad47-f539809592fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-lg btn-primary btn-block btn-next</value>
      <webElementGuid>929b4ffc-466f-40c1-8226-ceb2e785e884</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/Registration?option=Paid</value>
      <webElementGuid>61649e2e-b7b8-4b03-a616-bd9e8efe8be9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                    View Packages
                                </value>
      <webElementGuid>fd76acc2-475e-4264-ae6d-a959f43faa72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;signAsPaidButton&quot;)</value>
      <webElementGuid>d011b356-f351-409a-a10b-755be800b677</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>30e034a6-454c-4311-ab3d-328065258330</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>signAsPaidButton</value>
      <webElementGuid>9f36c7b1-bed9-4cad-82c2-e90749c0cd0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-lg btn-primary btn-block btn-next</value>
      <webElementGuid>98898893-c343-48c3-afd7-ef83f4605e0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/Registration?option=Paid</value>
      <webElementGuid>362de359-0958-4ac6-8572-8007d8a99df2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                    View Packages
                                </value>
      <webElementGuid>73e48e26-758e-48db-a7ab-7f32da627a02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;signAsPaidButton&quot;)</value>
      <webElementGuid>3b54e52f-0cd3-4a0a-8f65-9ca830ccd026</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='signAsPaidButton']</value>
      <webElementGuid>f023aacc-6f2b-4919-a4f5-801ac127ef7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='registrationForm']/div[2]/div[3]/div[2]/a</value>
      <webElementGuid>4f40d48f-cbcc-4b3c-bcab-b88ed38b787e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'View Packages')]</value>
      <webElementGuid>06afea2b-fbfc-4034-a5f4-3e722ad80e10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Try for Free!'])[1]/following::a[1]</value>
      <webElementGuid>01929905-72a5-4682-b337-61be84aa62a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TOEIC'])[1]/following::a[2]</value>
      <webElementGuid>e8e5b803-3039-43bd-bb76-518019985838</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='View Packages']/parent::*</value>
      <webElementGuid>be923d2b-415a-4668-ad7a-b4347951b59a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/Registration?option=Paid')]</value>
      <webElementGuid>7048ee5f-ef7a-4a05-b9ab-26e29e316cf2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a</value>
      <webElementGuid>203ca9a4-8a5e-4516-b24a-3fc65ec87e2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'signAsPaidButton' and @href = '/Registration?option=Paid' and (text() = '
                                    View Packages
                                ' or . = '
                                    View Packages
                                ')]</value>
      <webElementGuid>2c6121e0-a442-4ae6-a61e-92a939ce1e56</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
