<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_NEXT PERSONALISE</name>
   <tag></tag>
   <elementGuidId>68e21c9b-a4dd-4f3c-bea2-3a8f00343f3c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='saveRegistrationBtn']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#saveRegistrationBtn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9c50dcab-683c-45ce-9e05-4500d43c3737</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btn-xl btn-next width-full</value>
      <webElementGuid>8484e98e-8b22-4566-b23f-70cb2a4c355b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>saveRegistrationBtn</value>
      <webElementGuid>9e191805-c138-48a4-9627-9a12eaf2993f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>NEXT: PERSONALISE</value>
      <webElementGuid>bf0327c5-a80a-4832-aa18-f7c5f6ab28ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;saveRegistrationBtn&quot;)</value>
      <webElementGuid>9a2b3c7a-9f86-48f0-861c-be6ee6c11adc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ad7a0509-a2db-48b2-a3ea-e5d2e3daadc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btn-xl btn-next width-full</value>
      <webElementGuid>fc187762-b4f7-45a1-ad0d-e5a6af2242dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>saveRegistrationBtn</value>
      <webElementGuid>ab1916ee-2e68-430b-8e2b-7382b86cd60e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>NEXT: PERSONALISE</value>
      <webElementGuid>0aafdba9-960d-475b-90d8-7d0affd4e62a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;saveRegistrationBtn&quot;)</value>
      <webElementGuid>fafb63a4-1363-4712-9bff-f96a9da6a3a2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='saveRegistrationBtn']</value>
      <webElementGuid>bfb9757d-fc0f-40fc-94ed-123b6c1f451b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mainUserContent']/div/div[2]/div/div/div/div[3]/div/button</value>
      <webElementGuid>84f8036c-6fcd-444a-b40a-e8f980a58555</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login with Facebook'])[1]/following::button[1]</value>
      <webElementGuid>c6385aff-d1e3-47e1-aa7d-ddeb26c7a0fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login with Google'])[1]/following::button[1]</value>
      <webElementGuid>30a48c3b-e273-442a-af6e-f1dfa46df88d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='terms of use'])[1]/preceding::button[1]</value>
      <webElementGuid>c3768c86-519c-4e91-b860-ce7a3ce3bcb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='privacy notice'])[1]/preceding::button[1]</value>
      <webElementGuid>b261b9cf-a5f0-4d75-903b-194000b55158</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='NEXT: PERSONALISE']/parent::*</value>
      <webElementGuid>bd7baea1-7b95-4e00-916f-3074d90aaae8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/button</value>
      <webElementGuid>526256d2-d54f-4354-8b7a-7d9a04a0464d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'saveRegistrationBtn' and (text() = 'NEXT: PERSONALISE' or . = 'NEXT: PERSONALISE')]</value>
      <webElementGuid>3abcdb72-2020-4958-9399-685f99f96e9b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
