<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_YES, CORRECT</name>
   <tag></tag>
   <elementGuidId>f04d1a10-e253-4972-a223-88cbfa6dbd30</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='correct-btn']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#correct-btn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9f37547a-cd39-4346-84a7-da80901274ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>correct-btn</value>
      <webElementGuid>e3a6d981-5b9a-46b6-bdb2-8880aa4efcd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a12d3fbe-ab0f-4920-9961-0d20da5d92f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btn-xl border-radius-10px btn-next</value>
      <webElementGuid>ef863db6-42b8-4f79-8dd6-f07466c37e33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dismiss</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>7a33b91e-e4a7-4df2-9be1-059e11eaabff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-celpip-url</name>
      <type>Main</type>
      <value>https://celpip-rc.azurewebsites.net/</value>
      <webElementGuid>0d8dc315-def8-4b02-a8f9-9d7478ac5536</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-app-url</name>
      <type>Main</type>
      <value>https://staging-e2v2-rc.e2language.com/</value>
      <webElementGuid>dddd404e-2b63-4af4-9fab-f7f056c5d3e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                    YES, CORRECT
                </value>
      <webElementGuid>92f81b36-ba4b-4352-923f-cd288c66230d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;correct-btn&quot;)</value>
      <webElementGuid>801fd389-5105-41b9-a57f-622d5abd8fb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9b8b43bb-ffff-4ac3-85bc-bd03ae3b025c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>correct-btn</value>
      <webElementGuid>167326c8-ffae-4dad-869d-de97788f5f5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>49b8d320-9a96-47fd-916d-8d7140f327c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btn-xl border-radius-10px btn-next</value>
      <webElementGuid>c71309c3-37f1-4c1c-88ba-46084117bcfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dismiss</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>207afb6a-d8dc-4903-9721-724ebf208cd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-celpip-url</name>
      <type>Main</type>
      <value>https://celpip-rc.azurewebsites.net/</value>
      <webElementGuid>ff5f6d78-e146-48e9-a229-601468763387</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-app-url</name>
      <type>Main</type>
      <value>https://staging-e2v2-rc.e2language.com/</value>
      <webElementGuid>c6a1a245-eccb-4fd3-9664-09d87ecd4173</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                    YES, CORRECT
                </value>
      <webElementGuid>f97fbdc0-3f78-46d4-b7d9-b43bf47c5840</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;correct-btn&quot;)</value>
      <webElementGuid>3baaaca0-1b01-47cb-b3bd-b3a047ac0b9a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='correct-btn']</value>
      <webElementGuid>26e99e26-25a9-46b2-8c4f-f7b0f8aafdae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='emailVerificationReg']/div/div/div[3]/button</value>
      <webElementGuid>3b4d8640-fd2f-4d4b-98c6-569f1f515946</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='std1.re@mailinator.com'])[1]/following::button[1]</value>
      <webElementGuid>2f4660b9-0e01-4307-8713-718fda55838f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Is this correct?'])[1]/following::button[1]</value>
      <webElementGuid>85095538-7c37-4071-babf-c98aa2fd9d0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No, change email'])[1]/preceding::button[1]</value>
      <webElementGuid>17b26ac2-b873-4021-a4eb-580f07e96852</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Your email address has been used from last register. Do you want to continue using the account?'])[1]/preceding::button[2]</value>
      <webElementGuid>0e9c7fe1-4a84-4671-ad3d-c3962af7a011</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='YES, CORRECT']/parent::*</value>
      <webElementGuid>a6625ee6-ae98-4288-9394-41087849452a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[3]/div/div/div[3]/button</value>
      <webElementGuid>9c8dc5ba-97f9-4cee-86e1-0a36ac1446da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'correct-btn' and @type = 'button' and (text() = '
                    YES, CORRECT
                ' or . = '
                    YES, CORRECT
                ')]</value>
      <webElementGuid>1911808b-61c3-4cbe-8f86-a91af20ba5f0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
