<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_activationWarning</name>
   <tag></tag>
   <elementGuidId>483346f3-a654-4889-9683-a2da2455691a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='alertnotification']/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.m-b-sm</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2b090b6b-6bff-48fd-8787-71b973b019f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>m-b-sm</value>
      <webElementGuid>11760751-120b-417a-be7c-bb4b89337758</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Your account is activated however in order to receive notifications, you need to verify your email address. An email with a verification link has been sent to the email address provided by you during registration. Please check your inbox or spam folder to verify your account.</value>
      <webElementGuid>6c3e34f8-dffd-4d00-8fb4-e8f965c866f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;alertnotification&quot;)/div[@class=&quot;m-b-sm&quot;]</value>
      <webElementGuid>6c7450a1-acc2-4b84-ad14-5746d7a26251</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='alertnotification']/div</value>
      <webElementGuid>cc1d1555-9dcb-4c80-af2e-ef4dd191b5f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact Us'])[1]/following::div[16]</value>
      <webElementGuid>e6e2fa08-1d76-4acc-8fd9-3d3a2c319acc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact Support'])[1]/following::div[17]</value>
      <webElementGuid>c0abfda2-8d12-4e2a-8c96-02efb8338b2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Welcome Back, std1!'])[1]/preceding::div[1]</value>
      <webElementGuid>8505cc17-a79e-4571-92bc-54b7fe257900</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Progress'])[1]/preceding::div[1]</value>
      <webElementGuid>db5bd3b6-9a37-4713-9805-5372333f2ea9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Your account is activated however in order to receive notifications, you need to verify your email address. An email with a verification link has been sent to the email address provided by you during registration. Please check your inbox or spam folder to verify your account.']/parent::*</value>
      <webElementGuid>57e1b89b-816a-4979-8490-7578bec6f665</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[2]/div/div/div/div/div</value>
      <webElementGuid>9b47ff57-0037-4680-8fdc-973db8bfb171</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Your account is activated however in order to receive notifications, you need to verify your email address. An email with a verification link has been sent to the email address provided by you during registration. Please check your inbox or spam folder to verify your account.' or . = 'Your account is activated however in order to receive notifications, you need to verify your email address. An email with a verification link has been sent to the email address provided by you during registration. Please check your inbox or spam folder to verify your account.')]</value>
      <webElementGuid>868c38b8-2a43-4daa-940c-d4467c130c33</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
