<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_CELPIP General LS</name>
   <tag></tag>
   <elementGuidId>bb06c484-3e1f-468a-9dd1-9ca0976d77ac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='registrationForm']/div[2]/div[2]/div/div[8]/label/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>7d1f11a4-65f0-491c-a15d-c5906f9c6ff6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>box</value>
      <webElementGuid>fef50c4f-14f5-4dc5-83e6-702bad77d476</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                            CELPIP General LS
                                        </value>
      <webElementGuid>fc425a4a-83f2-4634-b6bd-37e34a07c2d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;registrationForm&quot;)/div[@class=&quot;panel-body&quot;]/div[@class=&quot;form-group&quot;]/div[@class=&quot;exam-type-option&quot;]/div[@class=&quot;option&quot;]/label[1]/span[@class=&quot;box&quot;]</value>
      <webElementGuid>6d7422ac-79ce-44df-98c6-2b1426f127c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>255af096-f13f-40ce-8866-7bbe5e0ab8aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>box</value>
      <webElementGuid>c780ffa6-b7cf-40af-80ab-1433a94c2b6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                            CELPIP General LS
                                        </value>
      <webElementGuid>062a7ba5-a488-4af8-810e-6ddb777a8246</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;registrationForm&quot;)/div[@class=&quot;panel-body&quot;]/div[@class=&quot;form-group&quot;]/div[@class=&quot;exam-type-option&quot;]/div[@class=&quot;option&quot;]/label[1]/span[@class=&quot;box&quot;]</value>
      <webElementGuid>e329f195-15c9-4ae0-9f0a-9f417248bbb4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='registrationForm']/div[2]/div[2]/div/div[8]/label/span</value>
      <webElementGuid>71fc6b36-799e-4e2b-8da1-bfe2248c654f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CELPIP General'])[1]/following::span[1]</value>
      <webElementGuid>b97ab1e6-041a-464f-a66d-0d38aefbfd3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OET (Doctors)'])[1]/following::span[3]</value>
      <webElementGuid>a4cbca8f-85a6-4a41-bc09-0d361436dd7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TOEIC'])[1]/preceding::span[2]</value>
      <webElementGuid>91ac35fa-02ab-4966-8041-35a9d09bc35f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/label/span</value>
      <webElementGuid>a811aa71-6d4b-4514-81c6-24745a436647</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '
                                            CELPIP General LS
                                        ' or . = '
                                            CELPIP General LS
                                        ')]</value>
      <webElementGuid>687aa73e-fc76-447c-ba69-c701009cf9f9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
