<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_VERIFY</name>
   <tag></tag>
   <elementGuidId>c1c78818-7b5a-42e1-b240-b1002423e47a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'VERIFY EMAIL')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>43c42d97-a5c8-4766-b438-b18aa135ff06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.mailinator.com/linker?linkid=bd205e24-5895-4996-a62b-8fd020f4a0f0</value>
      <webElementGuid>3db51676-32c7-4d2f-84c3-4f437b7787a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f9168358-16ff-4d79-8019-6dc09ee0a6d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_other</value>
      <webElementGuid>0fc55fcc-6feb-499a-a8b6-64227e26d3f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>nofollow</value>
      <webElementGuid>a42524ae-cb19-4ffe-9ef0-8d36cc14af0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>VERIFY EMAIL</value>
      <webElementGuid>2d4ae1d2-29d1-45b8-aa82-0cd34f5b34f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/table[1]/tbody[1]/tr[1]/td[1]/table[@class=&quot;wrapper&quot;]/tbody[1]/tr[2]/td[@class=&quot;section&quot;]/table[@class=&quot;wrapper&quot;]/tbody[1]/tr[1]/td[@class=&quot;text-center&quot;]/a[@class=&quot;button&quot;]</value>
      <webElementGuid>dd9aebf1-9c22-42ca-86c3-c9f2bc52fbf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Mailinator/iframe_EmailBody</value>
      <webElementGuid>e480165c-f192-46a6-9b67-d3a1dfe3b225</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'VERIFY EMAIL')]</value>
      <webElementGuid>8881640f-8be9-4f52-a969-30bd13350f89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='support.e2language.com'])[1]/preceding::a[2]</value>
      <webElementGuid>07cdbe9b-4e60-44a5-907f-0245bed32f20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='VERIFY EMAIL']/parent::*</value>
      <webElementGuid>70a49699-8ab0-4c86-a7ed-4508434e5348</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.mailinator.com/linker?linkid=bd205e24-5895-4996-a62b-8fd020f4a0f0')]</value>
      <webElementGuid>d5ebc771-ca35-4537-8a56-4b2760bd424d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td/table/tbody/tr/td/a</value>
      <webElementGuid>9f049429-36fd-43d7-a487-4e54fe2870ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.mailinator.com/linker?linkid=bd205e24-5895-4996-a62b-8fd020f4a0f0' and (text() = 'VERIFY EMAIL' or . = 'VERIFY EMAIL')]</value>
      <webElementGuid>5eb1364c-1c16-473d-aa4b-6ec123d9fc60</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
