<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_InboxEmail</name>
   <tag></tag>
   <elementGuidId>1f6a6b9e-68d0-4cf8-b590-ee83c512b964</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[4]/div/div/table/tbody/tr/td[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>810869e7-990b-4f09-8762-0ce7f2866a55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>if (event.keyCode == 13) { showTheMessage('std-gzpfoie-1665238836-1363686902'); }</value>
      <webElementGuid>6db048dd-32b0-46b0-945b-a1b09cfebf88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>showTheMessage('std-gzpfoie-1665238836-1363686902');</value>
      <webElementGuid>ab3eea6f-891a-47b1-bed1-eda3fca1ba51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-binding</value>
      <webElementGuid>7e3e20df-9470-49e7-866d-d04abbc0fe31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                    Verify Your Email
                </value>
      <webElementGuid>a43e1d05-930c-4d8e-a2a8-32bc110f1ea0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;row_std-gzpfoie-1665238836-1363686902&quot;)/td[@class=&quot;ng-binding&quot;]</value>
      <webElementGuid>4b8dadec-c7fc-4dd0-ad7c-81edcb0a3210</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>9108883b-1eaf-4a0e-b771-fa11bb0f7567</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>if (event.keyCode == 13) { showTheMessage('std-gzpfoie-1665238836-1363686902'); }</value>
      <webElementGuid>5bb4d7fe-41fe-4373-b518-db5918e92a02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>showTheMessage('std-gzpfoie-1665238836-1363686902');</value>
      <webElementGuid>7cfa9a98-c220-4c0d-8efc-2fca3a74aa6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-binding</value>
      <webElementGuid>a74cf660-25b9-46b9-a8ea-a115d81fb7b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                    Verify Your Email
                </value>
      <webElementGuid>44086395-a3f4-4320-a1ed-6e7418cfedcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;row_std-gzpfoie-1665238836-1363686902&quot;)/td[@class=&quot;ng-binding&quot;]</value>
      <webElementGuid>f2205995-8c90-4a5d-af5e-988a6884e874</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//td[@onclick=&quot;showTheMessage('std-gzpfoie-1665238836-1363686902');&quot;])[2]</value>
      <webElementGuid>7bf08d23-04e5-4703-92d6-0f1471938018</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='row_std-gzpfoie-1665238836-1363686902']/td[3]</value>
      <webElementGuid>d230509d-1506-45e9-8f07-838077f2976f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='E2 Test Prep'])[1]/following::td[1]</value>
      <webElementGuid>447700f9-665c-43b3-89fe-9950b29b1c53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Received'])[2]/following::td[3]</value>
      <webElementGuid>33ce85a4-d899-4036-9600-27a4223f9598</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Free'])[1]/preceding::td[2]</value>
      <webElementGuid>22feccad-15eb-476c-a055-915faca90221</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Get Verified!'])[1]/preceding::td[2]</value>
      <webElementGuid>72cb342d-29dd-4a3c-9ae1-d0b7f45fb511</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/table/tbody/tr/td[3]</value>
      <webElementGuid>dbcdd637-64b9-4103-9be2-54be7934085e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '
                    Verify Your Email
                ' or . = '
                    Verify Your Email
                ')]</value>
      <webElementGuid>67d46986-89d9-4ceb-a010-99d508731611</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
