<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_CourseProInclude</name>
   <tag></tag>
   <elementGuidId>8427749a-74ff-455c-be36-e919fe14e787</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='course-progress-item-47319']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#course-progress-item-47319</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>48fa1c01-fff9-4c0a-a79e-494f163ef222</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>a448dc8b-7e0c-4332-ad19-a742d8ba38af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>course-progress-item-47319</value>
      <webElementGuid>347dc6f6-1b4a-4675-aafe-9a56016402fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>course-item course</value>
      <webElementGuid>fbd5ed6c-d5b8-4fa8-affc-35d3fd312825</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-course-id</name>
      <type>Main</type>
      <value>489</value>
      <webElementGuid>29cacb0d-f46c-432e-ae8f-9f2c1a098c30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-course-published-id</name>
      <type>Main</type>
      <value>47319</value>
      <webElementGuid>7146df5f-6dd6-4a1a-a0c2-7eb12a2b0eea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-package-id</name>
      <type>Main</type>
      <value>63426</value>
      <webElementGuid>54119cf8-b5f4-421b-903f-052e2b7ed317</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-total-lesson</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>57d46633-2e36-4bdc-ace8-a133e9a8547c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-total-lesson-completed</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>293a02d9-be40-49c1-ac3d-14929a00c3c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>COURSE TILE INCLUDE</value>
      <webElementGuid>d2db7d6d-88de-48b2-b5c0-01dfef465a97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;course-progress-item-47319&quot;)</value>
      <webElementGuid>240affd0-a447-429a-8954-b4f59926c9f7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='course-progress-item-47319']</value>
      <webElementGuid>25298484-64d8-48e7-a546-07381bdbdc18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='coursesPanel']/div[3]/ul/li/a</value>
      <webElementGuid>b84699f9-3293-4c91-84e7-7522bf599550</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Click on a Course to start learning!'])[1]/following::a[1]</value>
      <webElementGuid>a3383fed-6e09-440f-bc80-0647935117f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='completed'])[1]/following::a[1]</value>
      <webElementGuid>20f85446-497d-4153-9163-c3e2379f8c01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='COURSE TILE EXCLUDE'])[1]/preceding::a[1]</value>
      <webElementGuid>7cca1b46-8013-4823-83f4-ff3408bcead9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[17]</value>
      <webElementGuid>a266a157-1ea2-4fd1-8a48-125f0e629d94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/ul/li/a</value>
      <webElementGuid>787a8cf1-0424-4977-951f-4ccb661e1747</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and @id = 'course-progress-item-47319' and (text() = 'COURSE TILE INCLUDE' or . = 'COURSE TILE INCLUDE')]</value>
      <webElementGuid>a8ec32a0-50c3-4ba8-8983-daa53758584d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
