<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_ETSStandard</name>
   <tag></tag>
   <elementGuidId>846994d3-7f85-490f-a73a-448e2272f571</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='topicPrimary-2700']/div/h2/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#topicPrimary-2700 > div.panel-heading.has-badge > h2.panel-title > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c961589b-68bc-4b97-813c-a21822250058</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-parent</name>
      <type>Main</type>
      <value>#accordion-1142</value>
      <webElementGuid>6e402e53-ecb6-4abf-9596-9fef9b9e2443</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>collapse</value>
      <webElementGuid>b7689b33-b278-44a1-a4a2-78ea57976a8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#topic-2700</value>
      <webElementGuid>96872f6c-108c-4511-8020-412c4d8db92d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>de1b484d-a7c1-4b34-875c-6050c57de953</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ETS - Standard/Wizard </value>
      <webElementGuid>e9cacc92-da60-4bcc-800a-ae1cfa88d5a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;topicPrimary-2700&quot;)/div[@class=&quot;panel-heading has-badge&quot;]/h2[@class=&quot;panel-title&quot;]/a[1]</value>
      <webElementGuid>4426123d-02cf-4d02-b0df-f0f2a3c38c38</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='topicPrimary-2700']/div/h2/a</value>
      <webElementGuid>ce44b411-4477-41c3-a015-574193a281ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loading the activity'])[3]/following::a[1]</value>
      <webElementGuid>3c9f3fa9-bc5f-48f2-9c3e-2685c1ea1301</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submittable - Standard/Wizard'])[1]/following::a[1]</value>
      <webElementGuid>ee3ce556-3237-42b1-8b84-1c2c185cd2c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loading the activity'])[4]/preceding::a[1]</value>
      <webElementGuid>dd214371-3fb9-470f-88f8-3a351f210e6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#topic-2700')]</value>
      <webElementGuid>496e4c41-0837-48f0-8e18-14997757c520</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/h2/a</value>
      <webElementGuid>a87e9d33-8f86-488d-b952-535069f0cd2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#topic-2700' and (text() = 'ETS - Standard/Wizard ' or . = 'ETS - Standard/Wizard ')]</value>
      <webElementGuid>35b56ffe-57f9-4dc9-a00c-ded8ced79e69</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
