<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_MediaStandard</name>
   <tag></tag>
   <elementGuidId>b49267e4-6a68-49ec-925d-95d851b93d1c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='topicPrimary-2697']/div/h2/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h2.panel-title > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c8e41e40-b205-47a8-ad3e-0f0e31f73549</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-parent</name>
      <type>Main</type>
      <value>#accordion-1142</value>
      <webElementGuid>59f67919-d652-42c5-9ecb-67a55eb26051</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>collapse</value>
      <webElementGuid>791fe27d-2dcc-4057-b06b-eaf8506436d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#topic-2697</value>
      <webElementGuid>9da16919-7202-461c-9d22-98a92380c35b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>48004ebc-d33a-43e4-ae5c-cf45d585015a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Media - Standard/Wizard </value>
      <webElementGuid>5f8758aa-ef41-4598-9a9c-0ec32ad88458</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;topicPrimary-2697&quot;)/div[@class=&quot;panel-heading has-badge&quot;]/h2[@class=&quot;panel-title&quot;]/a[1]</value>
      <webElementGuid>6068f6ed-847a-4486-9e16-3c90ddd8a413</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='topicPrimary-2697']/div/h2/a</value>
      <webElementGuid>59fc9d07-87c3-4b68-8cec-fee08de1af31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PDF/VIDEO/DCBOARD'])[1]/following::a[1]</value>
      <webElementGuid>f181bd65-2b94-4794-af18-e7223aa434e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Test Activity'])[1]/following::a[2]</value>
      <webElementGuid>ac87836c-1089-422d-b1ec-bca9af2de7e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loading the activity'])[1]/preceding::a[1]</value>
      <webElementGuid>9398508f-e5ed-404d-810d-6bafde53993d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#topic-2697')]</value>
      <webElementGuid>c8ade4a3-1761-44a0-9ac9-b49fbfb74371</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h2/a</value>
      <webElementGuid>87fdbea3-85ed-43b7-90fb-c124a31dcbe8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#topic-2697' and (text() = 'Media - Standard/Wizard ' or . = 'Media - Standard/Wizard ')]</value>
      <webElementGuid>dfdd4629-298b-4773-9e9e-68164d47d6eb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
