<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_ScoreableStandard</name>
   <tag></tag>
   <elementGuidId>efe400c5-3d91-44cc-b478-18cdb7dcca7f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='topicPrimary-2698']/div/h2/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#topicPrimary-2698 > div.panel-heading.has-badge > h2.panel-title > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6082a5f2-fc59-4e77-8b33-2118454c3ae2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-parent</name>
      <type>Main</type>
      <value>#accordion-1142</value>
      <webElementGuid>8e8891f4-7a9d-4915-80a0-06f28d7316cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>collapse</value>
      <webElementGuid>d03d266c-9164-4882-8d89-956f167cc6db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#topic-2698</value>
      <webElementGuid>5a057b1b-8d28-4320-89d7-e21033935751</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>20c2d6d0-e548-4cfb-a834-3e244f84c962</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Scoreable - Standard/Wizard </value>
      <webElementGuid>185753cc-adfc-4574-a65d-602a1de4ebaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;topicPrimary-2698&quot;)/div[@class=&quot;panel-heading has-badge&quot;]/h2[@class=&quot;panel-title&quot;]/a[1]</value>
      <webElementGuid>07b5123f-020d-432d-87d0-3dc013f8379c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='topicPrimary-2698']/div/h2/a</value>
      <webElementGuid>1bb48f7b-5fc8-4242-a168-0464a0fba26a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loading the activity'])[1]/following::a[1]</value>
      <webElementGuid>c60b4ee5-41fa-43d4-adc8-267009832b01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Media - Standard/Wizard'])[1]/following::a[1]</value>
      <webElementGuid>1764b431-ee01-49fc-87fa-9655176a80fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loading the activity'])[2]/preceding::a[1]</value>
      <webElementGuid>9c047214-79b2-4e10-be18-b6349b64b79a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#topic-2698')]</value>
      <webElementGuid>fbc89d22-86c9-43c5-bd6d-7e0691ae3cbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/h2/a</value>
      <webElementGuid>c882b21e-4920-4088-8b47-1b516d59322c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#topic-2698' and (text() = 'Scoreable - Standard/Wizard ' or . = 'Scoreable - Standard/Wizard ')]</value>
      <webElementGuid>70055fdd-447e-4302-acbe-bc753f552609</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
