<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_SubmittableStandard</name>
   <tag></tag>
   <elementGuidId>c32ee598-8884-4b09-80db-9ad222d6fe31</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='topicPrimary-2699']/div/h2/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#topicPrimary-2699 > div.panel-heading.has-badge > h2.panel-title > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>9d3dd75f-4efd-4a38-a307-b16f5efb8e73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-parent</name>
      <type>Main</type>
      <value>#accordion-1142</value>
      <webElementGuid>765b0447-abb1-4e2c-813f-e9406b089652</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>collapse</value>
      <webElementGuid>290ce571-7436-4c2e-8f9b-d78eb2b1e9b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#topic-2699</value>
      <webElementGuid>6e06f0e7-8501-4577-8908-9f50e5fab8a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6b3abc27-e77b-4dc8-8b31-b54362e00dcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Submittable - Standard/Wizard </value>
      <webElementGuid>80f2da6b-962f-4594-a3f1-7848c60c6177</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;topicPrimary-2699&quot;)/div[@class=&quot;panel-heading has-badge&quot;]/h2[@class=&quot;panel-title&quot;]/a[1]</value>
      <webElementGuid>bf1072ab-bef8-4f19-b586-cb90e650e804</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='topicPrimary-2699']/div/h2/a</value>
      <webElementGuid>b8d76b00-9744-457b-a925-fbaad497ccfd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loading the activity'])[2]/following::a[1]</value>
      <webElementGuid>2aebb6b1-f8e7-4549-9594-4c9573e8e6e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Scoreable - Standard/Wizard'])[1]/following::a[1]</value>
      <webElementGuid>4577ddb6-cdb0-4bfd-aff6-5448cd109ca7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loading the activity'])[3]/preceding::a[1]</value>
      <webElementGuid>335ec17b-fbcc-4fc1-89b0-441d2f3394a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#topic-2699')]</value>
      <webElementGuid>1efa4ac9-24d8-48a2-b334-6d72a0fac07a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/h2/a</value>
      <webElementGuid>d81b43e9-baf2-4873-8625-02331176b462</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#topic-2699' and (text() = 'Submittable - Standard/Wizard ' or . = 'Submittable - Standard/Wizard ')]</value>
      <webElementGuid>4ee71c35-a452-475b-ad4c-25d4fdb16655</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
