<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_WizardMix</name>
   <tag></tag>
   <elementGuidId>56d66851-3d81-4176-a844-37fd419d55f7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='topicPrimary-2702']/div/h2/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#topicPrimary-2702 > div.panel-heading.has-badge > h2.panel-title > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>672ed9bc-372c-4d53-bec1-500d19d1888d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-parent</name>
      <type>Main</type>
      <value>#accordion-1142</value>
      <webElementGuid>59f8e8d7-18a0-4fc5-a99e-3c9de032c3fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>collapse</value>
      <webElementGuid>5024744c-6ded-49d5-b176-20bda213a7fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#topic-2702</value>
      <webElementGuid>9a665ee6-2e0e-4b6d-b065-19f1e715a194</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d4c9db02-09cc-4161-ab99-64bfa2f7ca2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Wizard Mix - All Widget </value>
      <webElementGuid>eb922923-d8d3-44f7-9423-5ba9c4b780fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;topicPrimary-2702&quot;)/div[@class=&quot;panel-heading has-badge&quot;]/h2[@class=&quot;panel-title&quot;]/a[1]</value>
      <webElementGuid>7bb4c312-71ce-4236-8629-b8aac6fe7698</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='topicPrimary-2702']/div/h2/a</value>
      <webElementGuid>d56147b4-11a7-4b0a-8a2d-40c95db91d0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loading the activity'])[4]/following::a[1]</value>
      <webElementGuid>ace155ca-91fa-4705-965f-5757f690ef05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ETS - Standard/Wizard'])[1]/following::a[1]</value>
      <webElementGuid>7c05f68e-fca9-4f74-ba7c-34e2e670ad1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loading the activity'])[5]/preceding::a[1]</value>
      <webElementGuid>1103526d-6432-4ac9-add4-cda5d583c010</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#topic-2702')]</value>
      <webElementGuid>8de6146f-2875-46e7-ab77-9f5e71f70bb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/h2/a</value>
      <webElementGuid>bd1ea9c3-3ee1-4e76-ba26-ba625a1459d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#topic-2702' and (text() = 'Wizard Mix - All Widget ' or . = 'Wizard Mix - All Widget ')]</value>
      <webElementGuid>104a141e-a35d-4add-b59b-fad5a1d120a6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
