<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Scoreable3</name>
   <tag></tag>
   <elementGuidId>7b113425-c6f9-4dbb-9887-a5ae1df84234</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='panel-25663']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#panel-25663</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>fbb9f88c-1367-47e1-8c8a-1210874f1330</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>panel-task topic-activity panel-25663</value>
      <webElementGuid>f901fc9e-dae1-471f-bcfd-4b84683cac33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>panel-25663</value>
      <webElementGuid>5cf10b76-dec0-4266-89a2-448d07f686b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Not Done  ActivityStandard Practice Scoreable - Choose Correct AudioTask not completed.</value>
      <webElementGuid>3d9fb582-d442-4c52-9f10-06a483cb1a0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;panel-25663&quot;)</value>
      <webElementGuid>09f4793f-c013-4814-9759-b8a0a5985faf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='panel-25663']</value>
      <webElementGuid>c902804c-1459-48f9-9e97-21230ae9d7f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='topic-2698']/div/div/div[3]/div</value>
      <webElementGuid>801c56cb-046a-4305-b813-cc38666d54e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Standard Practice Scoreable - Multi-Choice (multiple)'])[1]/following::div[3]</value>
      <webElementGuid>55872db7-dde5-408d-9de3-b96b80f54187</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Activity'])[13]/following::div[4]</value>
      <webElementGuid>8f5978f3-bf94-4f27-ab17-66e630a1da84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div[2]/div/div/div[3]/div</value>
      <webElementGuid>93d89f13-1c2e-425f-a8d3-7b26ce72ee10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'panel-25663' and (text() = 'Not Done  ActivityStandard Practice Scoreable - Choose Correct AudioTask not completed.' or . = 'Not Done  ActivityStandard Practice Scoreable - Choose Correct AudioTask not completed.')]</value>
      <webElementGuid>ad711737-d078-48c2-87be-2c3d2025d438</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
