<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Scoreable6</name>
   <tag></tag>
   <elementGuidId>6a3bb48b-104b-478e-811c-fa4c31c7664f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='panel-25666']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#panel-25666</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>4f21937f-e23a-4b72-b6bd-f170effb3b84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>panel-task topic-activity panel-25666</value>
      <webElementGuid>fcabcde5-1af6-4a66-ab24-98b83a24c0fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>panel-25666</value>
      <webElementGuid>38dec569-2459-4664-be51-376889a6cd80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Not Done  ActivityStandard Practice Scoreable - Gap Fill (dropdown)Task not completed.</value>
      <webElementGuid>a770df95-1829-4dce-8965-8b392be5b58f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;panel-25666&quot;)</value>
      <webElementGuid>4d68dac7-2b62-4dc9-ad12-5a8aa04e2f7f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='panel-25666']</value>
      <webElementGuid>868d171f-fb0e-43ba-8978-014cbda270fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='topic-2698']/div/div[2]/div[3]/div</value>
      <webElementGuid>3d75fa02-d29d-48fc-bd4b-52f873b1975a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Standard Practice Scoreable - Short Answer'])[1]/following::div[3]</value>
      <webElementGuid>938b909b-a961-4ee4-aabd-e9505ca46e94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Activity'])[16]/following::div[4]</value>
      <webElementGuid>7567993c-27e3-4e2b-84e5-8dd717d55592</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div[2]/div[3]/div</value>
      <webElementGuid>1190655a-90d3-4307-ad9f-f5db5a137573</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'panel-25666' and (text() = 'Not Done  ActivityStandard Practice Scoreable - Gap Fill (dropdown)Task not completed.' or . = 'Not Done  ActivityStandard Practice Scoreable - Gap Fill (dropdown)Task not completed.')]</value>
      <webElementGuid>7de415cf-8f2c-454b-b1af-66b6b5020475</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
