<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Scoreable8</name>
   <tag></tag>
   <elementGuidId>1a77ee30-6e20-4c07-8bc9-3109defebe71</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='panel-25668']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#panel-25668</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>37e97d45-bc86-4915-ba21-f2cc1b1e08ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>panel-task topic-activity panel-25668</value>
      <webElementGuid>5053ecfc-78ea-4a35-bcc8-12020d91e7cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>panel-25668</value>
      <webElementGuid>a5853ad2-45f6-4f98-9d1a-4060ca9db843</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Not Done  ActivityStandard Practice Scoreable - Highlight WordTask not completed.</value>
      <webElementGuid>35b4ced0-087a-424d-aa91-58ca24d1aec9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;panel-25668&quot;)</value>
      <webElementGuid>4ebac844-e7f0-45f4-bc36-95f643ba8567</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='panel-25668']</value>
      <webElementGuid>7909a3cb-a935-420d-8aac-d050a406bb09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='topic-2698']/div/div[3]/div[2]/div</value>
      <webElementGuid>2bfa0fa0-86c4-42e1-b254-f694322b6832</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Standard Practice Scoreable - Gap Fill (Text)'])[1]/following::div[3]</value>
      <webElementGuid>bf614897-afe2-4755-9a4c-e9e649ab43a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Activity'])[18]/following::div[4]</value>
      <webElementGuid>3762f313-7db8-447c-a875-99a0ba786c94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div[3]/div[2]/div</value>
      <webElementGuid>4b9bcec2-cb9d-43f4-9040-19c6f491ca19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'panel-25668' and (text() = 'Not Done  ActivityStandard Practice Scoreable - Highlight WordTask not completed.' or . = 'Not Done  ActivityStandard Practice Scoreable - Highlight WordTask not completed.')]</value>
      <webElementGuid>d15080cc-180a-4013-a535-b5c89343fcd9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
