<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Scoreable5</name>
   <tag></tag>
   <elementGuidId>989a3a92-1461-4e64-980b-4826f52fd7f0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='panel-25665']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#panel-25665</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a8c6aa6b-945c-4e24-bc0d-8a54e7017d98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>panel-task topic-activity panel-25665</value>
      <webElementGuid>f928d8ff-3672-4699-9cd6-ad07458cf306</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>panel-25665</value>
      <webElementGuid>3d91edf2-521c-4837-842e-098f4f722cd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Not Done  ActivityStandard Practice Scoreable - Short AnswerTask not completed.</value>
      <webElementGuid>45a082da-f694-4e28-b608-f66f0614cf9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;panel-25665&quot;)</value>
      <webElementGuid>aec7df7b-2921-40d1-9423-296aaf47aa23</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='panel-25665']</value>
      <webElementGuid>931d1d5c-83bc-4e5b-9ac9-e99356ef0316</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='topic-2698']/div/div[2]/div[2]/div</value>
      <webElementGuid>46639039-79f6-4307-95f9-9091d1039b54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Standard Practice Scoreable - Reorder Paragraph'])[1]/following::div[3]</value>
      <webElementGuid>3405b782-0b57-498e-a271-182caa488c41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Activity'])[15]/following::div[4]</value>
      <webElementGuid>1c4fb052-1745-4e2a-8344-2f5e19da00fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div[2]/div[2]/div</value>
      <webElementGuid>3dd7ac76-ffe1-4121-bf16-d5e5c987b21e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'panel-25665' and (text() = 'Not Done  ActivityStandard Practice Scoreable - Short AnswerTask not completed.' or . = 'Not Done  ActivityStandard Practice Scoreable - Short AnswerTask not completed.')]</value>
      <webElementGuid>2f840f07-80b3-4acf-91f4-c2e70ebd5323</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
