<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Scoreable1</name>
   <tag></tag>
   <elementGuidId>7b243e73-5d80-4fcc-829d-0da789c87e86</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='panel-25661']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#panel-25661</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>89d02126-6c76-4690-8965-0849679a1637</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>panel-task topic-activity panel-25661</value>
      <webElementGuid>2416a3e3-bfff-4db0-8453-c6932f47f7ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>panel-25661</value>
      <webElementGuid>716bc8fa-5052-4610-9644-bbfb6b2dbf25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Not Done  ActivityStandard Practice Scoreable - Multi-Choice (Single)Task not completed.</value>
      <webElementGuid>c08d1d36-dd16-4285-b717-2135e067669c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;panel-25661&quot;)</value>
      <webElementGuid>d9690bf3-729b-48e6-95c2-bd86ad45c2c7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='panel-25661']</value>
      <webElementGuid>4d09c219-bc44-4b32-a2d2-513fd48ded5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='topic-2698']/div/div/div/div</value>
      <webElementGuid>d5c17976-cd30-4607-8d4d-1ce2bb136222</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Not started yet'])[2]/following::div[5]</value>
      <webElementGuid>de4171f1-ee68-4eaf-a488-5f68f8e371b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Scoreable - Standard/Wizard'])[1]/following::div[6]</value>
      <webElementGuid>af614faf-686e-40b7-bb45-e0e542d50bfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div[2]/div/div/div/div</value>
      <webElementGuid>f7edb43b-4c7d-47fb-95a0-71187ef61e95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'panel-25661' and (text() = 'Not Done  ActivityStandard Practice Scoreable - Multi-Choice (Single)Task not completed.' or . = 'Not Done  ActivityStandard Practice Scoreable - Multi-Choice (Single)Task not completed.')]</value>
      <webElementGuid>7b16e5e3-dd48-40e3-8fa8-00ca57495551</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
