<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Scoreable10</name>
   <tag></tag>
   <elementGuidId>d6fd6ecd-9fd8-4e19-a831-83172ef94412</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='panel-25670']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#panel-25670</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3b24664b-fcec-4240-8a66-1dad6b32f366</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>panel-task topic-activity panel-25670</value>
      <webElementGuid>d7430aef-4ce7-4fe8-b677-0080c6519c90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>panel-25670</value>
      <webElementGuid>e3d7dede-725d-4e31-9ac4-a1a084ce35c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Not Done  ActivityStandard Practice Scoreable - Drag and DropTask not completed.</value>
      <webElementGuid>7e1529fd-4cde-44b3-a678-2ab9826dd00f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;panel-25670&quot;)</value>
      <webElementGuid>a243a5e6-d72e-4a44-a4de-fa363bea8034</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='panel-25670']</value>
      <webElementGuid>a226523a-38b0-4852-82c1-7710d38e3a2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='topic-2698']/div/div[4]/div/div</value>
      <webElementGuid>04f994f6-72eb-49e8-99bd-6a348cfb8a48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Standard Practice Scoreable - Pronunciation'])[1]/following::div[4]</value>
      <webElementGuid>dccc657a-a681-4709-99c7-c806df6d016d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Activity'])[20]/following::div[5]</value>
      <webElementGuid>8cf5565f-729b-48e0-afad-f056c7fcecec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div[4]/div/div</value>
      <webElementGuid>c7bb419a-d509-41d4-b34f-6e3748b35a9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'panel-25670' and (text() = 'Not Done  ActivityStandard Practice Scoreable - Drag and DropTask not completed.' or . = 'Not Done  ActivityStandard Practice Scoreable - Drag and DropTask not completed.')]</value>
      <webElementGuid>9e5133f3-94c2-4e0a-87fd-69f23cd5298f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
