<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Scoreable4</name>
   <tag></tag>
   <elementGuidId>e7d469b5-9a40-406e-b1ac-6efc335946b8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='panel-25664']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#panel-25664</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9e95c80e-e890-44f9-a53e-595fc4776fe5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>panel-task topic-activity panel-25664</value>
      <webElementGuid>2a04413c-8a35-4870-9d7d-a88bc210a228</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>panel-25664</value>
      <webElementGuid>1223d529-4f0d-4d1f-9f31-77930db40e7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Not Done  ActivityStandard Practice Scoreable - Reorder ParagraphTask not completed.</value>
      <webElementGuid>ae54d47f-8494-4776-9662-717900425b11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;panel-25664&quot;)</value>
      <webElementGuid>f9c6ab5f-662f-4fb6-a7d6-4f3be2d97c92</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='panel-25664']</value>
      <webElementGuid>274ee395-551d-4488-8130-a038d9c8b806</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='topic-2698']/div/div[2]/div/div</value>
      <webElementGuid>72ed830b-11d8-4d4e-bd2f-748679a14701</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Standard Practice Scoreable - Choose Correct Audio'])[1]/following::div[4]</value>
      <webElementGuid>ff4cbe83-f9f6-49cf-8e4d-4d3274ef4009</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Activity'])[14]/following::div[5]</value>
      <webElementGuid>32d90086-2c11-4694-b908-835b58d2b27a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div[2]/div/div</value>
      <webElementGuid>c5c77846-d647-495b-becf-38dd63a6fbea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'panel-25664' and (text() = 'Not Done  ActivityStandard Practice Scoreable - Reorder ParagraphTask not completed.' or . = 'Not Done  ActivityStandard Practice Scoreable - Reorder ParagraphTask not completed.')]</value>
      <webElementGuid>53481212-a147-479c-b10e-57b073471784</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
