<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Scoreable9</name>
   <tag></tag>
   <elementGuidId>a2a583d9-7839-40c3-9b2f-150b715e187c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='panel-25669']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#panel-25669</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0f27893c-7f5a-4d91-b881-0ac334b81e8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>panel-task topic-activity panel-25669</value>
      <webElementGuid>c6b4c334-7ebc-45ec-9d50-01daa1e3305b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>panel-25669</value>
      <webElementGuid>4d295feb-cb18-4f3b-9a67-83bd26c25337</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Not Done  ActivityStandard Practice Scoreable - PronunciationTask not completed.</value>
      <webElementGuid>8a81cbc9-7f28-4f77-8ed4-138e0e5270af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;panel-25669&quot;)</value>
      <webElementGuid>a933784b-a927-4bb4-8240-fd70fee0c352</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='panel-25669']</value>
      <webElementGuid>d83db04f-2383-401d-9f3b-0c4204cfcc06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='topic-2698']/div/div[3]/div[3]/div</value>
      <webElementGuid>dbbe3c8a-4647-4102-ae70-a4b8f58f00a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Standard Practice Scoreable - Highlight Word'])[1]/following::div[3]</value>
      <webElementGuid>b5e4a88e-2c3a-4c6e-b648-a5f614c4f39a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Activity'])[19]/following::div[4]</value>
      <webElementGuid>8a27b3d1-f0c1-465d-a640-5c09166f0a15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div[3]/div[3]/div</value>
      <webElementGuid>c8957768-9ab3-4da9-b91a-1810f3a6e299</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'panel-25669' and (text() = 'Not Done  ActivityStandard Practice Scoreable - PronunciationTask not completed.' or . = 'Not Done  ActivityStandard Practice Scoreable - PronunciationTask not completed.')]</value>
      <webElementGuid>508a9c08-007f-430b-be4c-d88f02254f64</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
