<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Scoreable7</name>
   <tag></tag>
   <elementGuidId>cf22e1c4-48e9-4173-97d3-12d1a580e94a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='panel-25667']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#panel-25667</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>af928a4c-f98c-41a8-824f-35df9c0e1079</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>panel-task topic-activity panel-25667</value>
      <webElementGuid>7a533837-8592-4759-94a9-9270c8cae29b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>panel-25667</value>
      <webElementGuid>9784519d-f1c9-4fe8-8b63-e1ed97b2749b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Not Done  ActivityStandard Practice Scoreable - Gap Fill (Text)Task not completed.</value>
      <webElementGuid>893dafd4-f4fd-43b9-8ad3-97534cc42e2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;panel-25667&quot;)</value>
      <webElementGuid>ced39804-c2d5-4fed-8f15-97925294f2a3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='panel-25667']</value>
      <webElementGuid>c11754c9-4160-44f8-aeda-98db0262b3d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='topic-2698']/div/div[3]/div/div</value>
      <webElementGuid>dcb27a8b-5b9f-4d17-8b64-a27273c4cd7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Standard Practice Scoreable - Gap Fill (dropdown)'])[1]/following::div[4]</value>
      <webElementGuid>567671e0-37e1-4b1a-a486-0e87f4d6bba6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Activity'])[17]/following::div[5]</value>
      <webElementGuid>6e53b764-4a35-4a70-a70e-132a9a4b577f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div[3]/div/div</value>
      <webElementGuid>c5b3d3c7-4e4c-4082-87b6-c0a4e5163d6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'panel-25667' and (text() = 'Not Done  ActivityStandard Practice Scoreable - Gap Fill (Text)Task not completed.' or . = 'Not Done  ActivityStandard Practice Scoreable - Gap Fill (Text)Task not completed.')]</value>
      <webElementGuid>d7895ba0-374d-4729-93f6-65417672027a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
