<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Scoreable2</name>
   <tag></tag>
   <elementGuidId>e643190d-7bd6-432e-b751-baa5c6de5b22</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='panel-25662']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#panel-25662</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5d4c3763-75c6-47b1-8a33-c1ff6102d96c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>panel-task topic-activity panel-25662</value>
      <webElementGuid>efac2709-5adc-4dff-ab8a-860ea8d0c3f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>panel-25662</value>
      <webElementGuid>9f784a96-545f-4749-a852-1f86e936614e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Not Done  ActivityStandard Practice Scoreable - Multi-Choice (multiple)Task not completed.</value>
      <webElementGuid>3f501508-d6f6-4b6e-b2d9-5fa151aa55af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;panel-25662&quot;)</value>
      <webElementGuid>5e5f0b6c-9e7d-41d6-bee7-9d2632754c9f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='panel-25662']</value>
      <webElementGuid>e9a1e679-5582-4b0b-aadc-ccba6279d798</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='topic-2698']/div/div/div[2]/div</value>
      <webElementGuid>6877aeac-12b0-4d2d-be74-92b306f24b19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Standard Practice Scoreable - Multi-Choice (Single)'])[1]/following::div[3]</value>
      <webElementGuid>9159afc0-658e-4e92-b270-b2147ca592bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Activity'])[12]/following::div[4]</value>
      <webElementGuid>a15af5d1-764a-4936-96fd-3f64bdf43c60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div[2]/div/div/div[2]/div</value>
      <webElementGuid>24a12edf-a279-4da4-9f0e-8580cccf3898</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'panel-25662' and (text() = 'Not Done  ActivityStandard Practice Scoreable - Multi-Choice (multiple)Task not completed.' or . = 'Not Done  ActivityStandard Practice Scoreable - Multi-Choice (multiple)Task not completed.')]</value>
      <webElementGuid>77bd5f75-f6c0-4461-b05c-e099c02f8d1b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
